package gaia.model;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaNPCTrader extends ModelGaia {
	ModelRenderer head;
    ModelRenderer headeyes;
	ModelRenderer headaccessory;
	ModelRenderer neck;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	public static ModelRenderer rightarm;
	public static ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer righthair;
	ModelRenderer lefthair;
	ModelRenderer righthairpin;
	ModelRenderer lefthairpin;
	ModelRenderer rightear;
	ModelRenderer leftear;
	ModelRenderer rightpauldron;
	ModelRenderer leftpauldron;
	ModelRenderer watch;
	ModelRenderer tail;
	ModelRenderer waist1;
	ModelRenderer waist2;
	ModelRenderer waist3;
	ModelRenderer rightleglower;
	ModelRenderer leftleglower;
	ModelRenderer rightfootlower;
	ModelRenderer leftfootlower;

	public ModelGaiaNPCTrader() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, 0F);
		this.head.setTextureSize(64, 32);
		this.setRotation(head, 0F, 0F, 0F);
		this.headeyes = new ModelRenderer(this, 24, 0);
		this.headeyes.addBox(-3F, -6F, -3.1F, 6, 6, 0);
		this.headeyes.setRotationPoint(0F, 1F, 0F);
		this.headeyes.setTextureSize(64, 32);
		this.setRotation(headeyes, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, 0F);
		this.headaccessory.setTextureSize(64, 32);
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.neck = new ModelRenderer(this, 0, 12);
		this.neck.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.neck.setRotationPoint(0F, 1F, 0F);
		this.neck.setTextureSize(64, 32);
		this.setRotation(neck, 0F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 16);
		this.bodytop.addBox(-2.5F, 0F, -1.5F, 5, 6, 3);
		this.bodytop.setRotationPoint(0F, 1F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.setRotation(bodytop, -0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 25);
		this.bodymiddle.addBox(-2F, 5.5F, -1.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.setRotation(bodymiddle, 0F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 25);
		this.bodymiddlebutton.addBox(-0.5F, 6F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 30);
		this.bodybottom.addBox(-3F, 8F, -2.5F, 6, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.setRotation(bodybottom, 0.0872665F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 36);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, 3F, -1.5F);
		this.rightchest.setTextureSize(64, 32);
		this.setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 0, 36);
		this.leftchest.mirror = true;
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, 3F, -1.5F);
		this.leftchest.setTextureSize(64, 32);
		this.setRotation(leftchest, 0.7853982F, -0.1745329F, -0.0872665F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 12, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.setRotation(rightarm, 0F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 12, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.setRotation(leftarm, 0F, 0F, -0.1745329F);
		this.rightleg = new ModelRenderer(this, 24, 12);
		this.rightleg.addBox(-1.5F, -1F, -1.5F, 3, 8, 3);
		this.rightleg.setRotationPoint(-2F, 11F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.setRotation(rightleg, -0.3490659F, -0.0872665F, -0.0349066F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1.5F, -1F, -1.5F, 3, 8, 3);
		this.leftleg.setRotationPoint(2F, 11F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.setRotation(leftleg, -0.3490659F, 0.0872665F, 0.0349066F);
		this.righthair = new ModelRenderer(this, 36, 14);
		this.righthair.addBox(-5F, -5F, 1.5F, 3, 9, 3);
		this.righthair.setRotationPoint(0F, 1F, 0F);
		this.righthair.setTextureSize(64, 32);
		this.setRotation(righthair, 0F, 0.0872665F, 0.1745329F);
		this.lefthair = new ModelRenderer(this, 36, 14);
		this.lefthair.addBox(2F, -5F, 1.5F, 3, 9, 3);
		this.lefthair.setRotationPoint(0F, 1F, 0F);
		this.lefthair.setTextureSize(64, 32);
		this.setRotation(lefthair, 0F, -0.0872665F, -0.1745329F);
		this.righthairpin = new ModelRenderer(this, 36, 26);
		this.righthairpin.addBox(-6F, -8F, 1F, 4, 4, 4);
		this.righthairpin.setRotationPoint(0F, 1F, 0F);
		this.righthairpin.setTextureSize(64, 32);
		this.setRotation(righthairpin, 0F, 0F, 0.1745329F);
		this.lefthairpin = new ModelRenderer(this, 52, 26);
		this.lefthairpin.addBox(2F, -8F, 1F, 4, 4, 4);
		this.lefthairpin.setRotationPoint(0F, 1F, 0F);
		this.lefthairpin.setTextureSize(64, 32);
		this.setRotation(lefthairpin, 0F, 0F, -0.1745329F);
		this.rightear = new ModelRenderer(this, 36, 34);
		this.rightear.addBox(-3F, -8.5F, -6F, 2, 8, 6);
		this.rightear.setRotationPoint(0F, 1F, 0F);
		this.rightear.setTextureSize(64, 32);
		this.setRotation(rightear, 0F, 0.2617994F, 0F);
		this.leftear = new ModelRenderer(this, 36, 34);
		this.leftear.addBox(1F, -8.5F, -6F, 2, 8, 6);
		this.leftear.setRotationPoint(0F, 1F, 0F);
		this.leftear.setTextureSize(64, 32);
		this.setRotation(leftear, 0F, -0.2617994F, 0F);
		this.rightpauldron = new ModelRenderer(this, 36, 48);
		this.rightpauldron.addBox(-2.5F, -1.5F, -1.5F, 3, 3, 3);
		this.rightpauldron.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightpauldron.setTextureSize(64, 32);
		this.setRotation(rightpauldron, 0F, 0F, 0.1745329F);
		this.leftpauldron = new ModelRenderer(this, 48, 48);
		this.leftpauldron.addBox(-0.5F, -1.5F, -1.5F, 3, 3, 3);
		this.leftpauldron.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftpauldron.setTextureSize(64, 32);
		this.setRotation(leftpauldron, 0F, 0F, -0.1745329F);
		this.watch = new ModelRenderer(this, 68, 0);
		this.watch.addBox(-3F, 8F, -2.5F, 1, 5, 5);
		this.watch.setRotationPoint(0F, 1F, 0F);
		this.watch.setTextureSize(64, 32);
		this.setRotation(watch, 0F, 0F, 0.1745329F);
		this.tail = new ModelRenderer(this, 68, 10);
		this.tail.addBox(-1.5F, 6F, -5F, 3, 3, 3);
		this.tail.setRotationPoint(0F, 1F, 0F);
		this.tail.setTextureSize(64, 32);
		this.setRotation(tail, 0.7853982F, 0F, 0F);
		this.waist1 = new ModelRenderer(this, 68, 16);
		this.waist1.addBox(-3.5F, 8.5F, -3.5F, 7, 2, 7);
		this.waist1.setRotationPoint(0F, 1F, 0F);
		this.waist1.setTextureSize(64, 32);
		this.setRotation(waist1, 0F, 0F, 0F);
		this.waist2 = new ModelRenderer(this, 68, 25);
		this.waist2.addBox(-4F, 10.5F, -4F, 8, 3, 8);
		this.waist2.setRotationPoint(0F, 1F, 0F);
		this.waist2.setTextureSize(64, 32);
		this.setRotation(waist2, 0F, 0F, 0F);
		this.waist3 = new ModelRenderer(this, 68, 36);
		this.waist3.addBox(-4.5F, 13.5F, -4.5F, 9, 5, 9);
		this.waist3.setRotationPoint(0F, 1F, 0F);
		this.waist3.setTextureSize(64, 32);
		this.setRotation(waist3, 0F, 0F, 0F);
		this.rightleglower = new ModelRenderer(this, 68, 50);
		this.rightleglower.addBox(-1.5F, 4.5F, 1.5F, 3, 8, 2);
		this.rightleglower.setRotationPoint(-2F, 11F, 0F);
		this.rightleglower.setTextureSize(64, 32);
		this.setRotation(rightleglower, -0.3490659F, -0.0872665F, -0.0349066F);
		this.leftleglower = new ModelRenderer(this, 68, 50);
		this.leftleglower.addBox(-1.5F, 4.5F, 1.5F, 3, 8, 2);
		this.leftleglower.setRotationPoint(2F, 11F, 0F);
		this.leftleglower.setTextureSize(64, 32);
		this.setRotation(leftleglower, -0.3490659F, 0.0872665F, 0.0349066F);
		this.rightfootlower = new ModelRenderer(this, 68, 60);
		this.rightfootlower.addBox(-1.5F, 11.5F, -5F, 3, 1, 3);
		this.rightfootlower.setRotationPoint(-2F, 11F, 0F);
		this.rightfootlower.setTextureSize(64, 32);
		this.setRotation(rightfootlower, 0.0872665F, -0.0872665F, -0.0349066F);
		this.leftfootlower = new ModelRenderer(this, 68, 60);
		this.leftfootlower.addBox(-1.5F, 11.5F, -5F, 3, 1, 3);
		this.leftfootlower.setRotationPoint(2F, 11F, 0F);
		this.leftfootlower.setTextureSize(64, 32);
		this.setRotation(leftfootlower, 0.0872665F, 0.0872665F, 0.0349066F);
		
		this.convertToChild(head, rightear);
		this.convertToChild(head, leftear);
		this.convertToChild(head, righthair);
		this.convertToChild(head, lefthair);
		this.convertToChild(head, righthairpin);
		this.convertToChild(head, lefthairpin);
		this.convertToChild(rightarm, rightpauldron);
		this.convertToChild(leftarm, leftpauldron);
		this.convertToChild(rightleg, rightleglower);
		this.convertToChild(rightleg, rightfootlower);
		this.convertToChild(leftleg, leftleglower);
		this.convertToChild(leftleg, leftfootlower);
	}

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
		super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.setRotationAngles(limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale, entityIn);
		this.head.render(scale);
		this.headaccessory.render(scale);
		this.neck.render(scale);
		this.bodytop.render(scale);
		this.bodymiddle.render(scale);
		this.bodymiddlebutton.render(scale);
		this.bodybottom.render(scale);
		this.rightchest.render(scale);
		this.leftchest.render(scale);
		this.rightarm.render(scale);
		this.leftarm.render(scale);
		this.rightleg.render(scale);
		this.leftleg.render(scale);
//		this.righthair.render(scale);
//		this.lefthair.render(scale);
//		this.righthairpin.render(scale);
//		this.lefthairpin.render(scale);
//		this.rightear.render(scale);
//		this.leftear.render(scale);
//		this.rightpauldron.render(scale);
//		this.leftpauldron.render(scale);
		this.watch.render(scale);
		this.tail.render(scale);
		this.waist1.render(scale);
		this.waist2.render(scale);
		this.waist3.render(scale);
//		this.rightleglower.render(scale);
//		this.leftleglower.render(scale);
//		this.rightfootlower.render(scale);
//		this.leftfootlower.render(scale);

		if (entityIn.ticksExisted % 60 == 0 && limbSwingAmount <= 0.1F) {
			this.headeyes.render(scale);
		}
	}

	public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
		//head
		this.head.rotateAngleY = netHeadYaw / 57.295776F;
		this.head.rotateAngleX = headPitch / 57.295776F;
		this.headeyes.rotateAngleY = this.head.rotateAngleY;
		this.headeyes.rotateAngleX = this.head.rotateAngleX;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
//		this.righthair.rotateAngleY = this.head.rotateAngleY + 0.0872665F;
//		this.lefthair.rotateAngleY = this.head.rotateAngleY - 0.0872665F;
//		this.righthairpin.rotateAngleY = this.head.rotateAngleY + 0.0872665F;
//		this.lefthairpin.rotateAngleY = this.head.rotateAngleY - 0.0872665F;
		
		//arms
		this.rightarm.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float)Math.PI) * 0.8F * limbSwingAmount * 0.5F;
		this.leftarm.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 0.8F * limbSwingAmount * 0.5F;
		
		this.rightarm.rotateAngleZ = 0.0F;
		this.leftarm.rotateAngleZ = 0.0F;

        this.rightarm.rotateAngleZ += (MathHelper.cos(ageInTicks * 0.09F) * 0.025F + 0.025F) + 0.1745329F;
        this.rightarm.rotateAngleX += MathHelper.sin(ageInTicks * 0.067F) * 0.025F;
        this.leftarm.rotateAngleZ -= (MathHelper.cos(ageInTicks * 0.09F) * 0.025F + 0.025F) + 0.1745329F;
        this.leftarm.rotateAngleX -= MathHelper.sin(ageInTicks * 0.067F) * 0.025F;
		
		//body
		this.tail.rotateAngleY = MathHelper.cos(limbSwing * 0.6662F) * 0.5F * limbSwingAmount;
		
		//legs
		this.rightleg.rotateAngleX = (MathHelper.cos(limbSwing * 0.6662F) * 0.5F * limbSwingAmount) * 0.5F;
		this.rightleg.rotateAngleX -= 0.3490659F;
		this.leftleg.rotateAngleX = (MathHelper.cos(limbSwing * 0.6662F + (float)Math.PI) * 0.5F * limbSwingAmount) * 0.5F;
		this.leftleg.rotateAngleX -= 0.3490659F;
	}
}
