package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaWerecat extends ModelBase {
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer leash;
	ModelRenderer rightear;
	ModelRenderer leftear;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightarmlower;
	ModelRenderer leftarmlower;
	public static ModelRenderer righthand;
	public static ModelRenderer lefthand;
	ModelRenderer tail;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer rightleglower;
	ModelRenderer leftleglower;
	ModelRenderer chain;
	ModelRenderer rightfootlower;
	ModelRenderer leftfootlower;
	ModelRenderer rightfoot;
	ModelRenderer leftfoot;

	public ModelGaiaWerecat() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, -2.5F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, -2.5F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.leash = new ModelRenderer(this, 36, 21);
		this.leash.addBox(-1.5F, -0.5F, -2.5F, 3, 1, 3);
		this.leash.setRotationPoint(0F, 1F, -2F);
		this.leash.setTextureSize(64, 32);
		this.leash.mirror = true;
		this.setRotation(leash, 0.2617994F, 0F, 0F);
		this.rightear = new ModelRenderer(this, 36, 14);
		this.rightear.addBox(-4.5F, -10F, -1.5F, 4, 4, 3);
		this.rightear.setRotationPoint(0F, 1F, -2.5F);
		this.rightear.setTextureSize(64, 32);
		this.rightear.mirror = true;
		this.setRotation(rightear, 0F, 0F, 0F);
		this.leftear = new ModelRenderer(this, 50, 14);
		this.leftear.addBox(0.5F, -10F, -1.5F, 4, 4, 3);
		this.leftear.setRotationPoint(0F, 1F, -2.5F);
		this.leftear.setTextureSize(64, 32);
		this.leftear.mirror = true;
		this.setRotation(leftear, 0F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -1F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, 1F, -3F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, 0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -1.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, -3F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0.2617994F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -2.5F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, -3F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.3490659F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, 3F, -4F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 0.9599311F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, 3F, -4F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 0.9599311F, -0.1745329F, -0.0872665F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 8, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, -2.5F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, -0.1745329F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 8, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, -2.5F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, -0.1745329F, 0F, -0.1745329F);
		this.rightarmlower = new ModelRenderer(this, 36, 25);
		this.rightarmlower.addBox(-2.5F, 2F, -1.5F, 2, 8, 3);
		this.rightarmlower.setRotationPoint(-2.5F, 2.5F, -2.5F);
		this.rightarmlower.setTextureSize(64, 32);
		this.rightarmlower.mirror = true;
		this.setRotation(rightarmlower, -0.1745329F, 0F, 0.1745329F);
		this.leftarmlower = new ModelRenderer(this, 46, 25);
		this.leftarmlower.addBox(0.5F, 2F, -1.5F, 2, 8, 3);
		this.leftarmlower.setRotationPoint(2.5F, 2.5F, -2.5F);
		this.leftarmlower.setTextureSize(64, 32);
		this.leftarmlower.mirror = true;
		this.setRotation(leftarmlower, -0.1745329F, 0F, -0.1745329F);
		this.righthand = new ModelRenderer(this, 36, 36);
		this.righthand.addBox(-2.5F, 8F, -2F, 2, 4, 4);
		this.righthand.setRotationPoint(-2.5F, 2.5F, -2.5F);
		this.righthand.setTextureSize(64, 32);
		this.righthand.mirror = true;
		this.setRotation(righthand, -0.1745329F, 0F, 0.0872665F);
		this.lefthand = new ModelRenderer(this, 48, 36);
		this.lefthand.addBox(0.5F, 8F, -2F, 2, 4, 4);
		this.lefthand.setRotationPoint(2.5F, 2.5F, -2.5F);
		this.lefthand.setTextureSize(64, 32);
		this.lefthand.mirror = true;
		this.setRotation(lefthand, -0.1745329F, 0F, -0.0872665F);
		this.tail = new ModelRenderer(this, 36, 44);
		this.tail.addBox(-1F, 7F, -3.5F, 2, 10, 2);
		this.tail.setRotationPoint(0F, 1F, -2F);
		this.tail.setTextureSize(64, 32);
		this.tail.mirror = true;
		this.setRotation(tail, 0.6108652F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 64, 0);
		this.rightleg.addBox(-1F, -2F, -2F, 2, 6, 4);
		this.rightleg.setRotationPoint(-2F, 11F, -1F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, -0.3490659F, 0F, -0.0349066F);
		this.leftleg = new ModelRenderer(this, 64, 0);
		this.leftleg.addBox(-1F, -2F, -2F, 2, 6, 4);
		this.leftleg.setRotationPoint(2F, 11F, -1F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, -0.3490659F, 0F, 0.0349066F);
		this.rightleglower = new ModelRenderer(this, 64, 14);
		this.rightleglower.addBox(-1F, 1F, -4.5F, 2, 6, 2);
		this.rightleglower.setRotationPoint(-2F, 11F, -1F);
		this.rightleglower.setTextureSize(64, 32);
		this.rightleglower.mirror = true;
		this.setRotation(rightleglower, 0.6108652F, 0F, -0.0349066F);
		this.leftleglower = new ModelRenderer(this, 64, 14);
		this.leftleglower.addBox(-1F, 1F, -4.5F, 2, 6, 2);
		this.leftleglower.setRotationPoint(2F, 11F, -1F);
		this.leftleglower.setTextureSize(64, 32);
		this.leftleglower.mirror = true;
		this.setRotation(leftleglower, 0.6108652F, 0F, 0.0349066F);
		this.chain = new ModelRenderer(this, 64, 10);
		this.chain.addBox(-1.5F, 4F, -5F, 3, 1, 3);
		this.chain.setRotationPoint(2F, 11F, -1F);
		this.chain.setTextureSize(64, 32);
		this.chain.mirror = true;
		this.setRotation(chain, 0.6108652F, 0F, 0.0349066F);
		this.rightfootlower = new ModelRenderer(this, 64, 30);
		this.rightfootlower.addBox(-1.5F, 10F, -7.5F, 3, 1, 2);
		this.rightfootlower.setRotationPoint(-2F, 11F, -1F);
		this.rightfootlower.setTextureSize(64, 32);
		this.rightfootlower.mirror = true;
		this.setRotation(rightfootlower, 0.4363323F, 0F, -0.0349066F);
		this.leftfootlower = new ModelRenderer(this, 64, 30);
		this.leftfootlower.addBox(-1.5F, 10F, -7.5F, 3, 1, 2);
		this.leftfootlower.setRotationPoint(2F, 11F, -1F);
		this.leftfootlower.setTextureSize(64, 32);
		this.leftfootlower.mirror = true;
		this.setRotation(leftfootlower, 0.4363323F, 0F, 0.0349066F);
		this.rightfoot = new ModelRenderer(this, 64, 22);
		this.rightfoot.addBox(-1.5F, 5.5F, 2.5F, 3, 6, 2);
		this.rightfoot.setRotationPoint(-2F, 11F, -1F);
		this.rightfoot.setTextureSize(64, 32);
		this.rightfoot.mirror = true;
		this.setRotation(rightfoot, -0.3490659F, 0F, -0.0349066F);
		this.leftfoot = new ModelRenderer(this, 64, 22);
		this.leftfoot.addBox(-1.5F, 5.5F, 2.5F, 3, 6, 2);
		this.leftfoot.setRotationPoint(2F, 11F, -1F);
		this.leftfoot.setTextureSize(64, 32);
		this.leftfoot.mirror = true;
		this.setRotation(leftfoot, -0.3490659F, 0F, 0.0349066F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.leash.render(par7);
		this.rightear.render(par7);
		this.leftear.render(par7);
		this.bodytop.render(par7);
		this.bodymiddle.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.rightarm.render(par7);
		this.leftarm.render(par7);
		this.rightarmlower.render(par7);
		this.leftarmlower.render(par7);
		this.righthand.render(par7);
		this.lefthand.render(par7);
		this.tail.render(par7);
		this.rightleg.render(par7);
		this.leftleg.render(par7);
		this.rightleglower.render(par7);
		this.leftleglower.render(par7);
		this.chain.render(par7);
		this.rightfootlower.render(par7);
		this.leftfootlower.render(par7);
		this.rightfoot.render(par7);
		this.leftfoot.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.rightear.rotateAngleY = this.head.rotateAngleY;
		this.rightear.rotateAngleX = this.head.rotateAngleX;
		this.leftear.rotateAngleY = this.head.rotateAngleY;
		this.leftear.rotateAngleX = this.head.rotateAngleX;
		this.righthand.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2 * 0.5F;
		this.lefthand.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2 * 0.5F;
		this.rightarm.rotateAngleX = this.righthand.rotateAngleX - 0.1745329F;
		this.leftarm.rotateAngleX = this.lefthand.rotateAngleX - 0.1745329F;
		this.rightarmlower.rotateAngleX = this.righthand.rotateAngleX - 0.1745329F;
		this.leftarmlower.rotateAngleX = this.lefthand.rotateAngleX - 0.1745329F;
		this.righthand.rotateAngleX -= 0.1745329F;
		this.lefthand.rotateAngleX -= 0.1745329F;
		this.tail.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.5F * par2;
		this.rightleglower.rotateAngleX = this.rightleg.rotateAngleX + 0.6108652F;
		this.leftleglower.rotateAngleX = this.leftleg.rotateAngleX + 0.6108652F;
		this.chain.rotateAngleX = this.leftleg.rotateAngleX + 0.6108652F;
		this.rightfoot.rotateAngleX = this.rightleg.rotateAngleX - 0.3490659F;
		this.leftfoot.rotateAngleX = this.leftleg.rotateAngleX - 0.3490659F;
		this.rightfootlower.rotateAngleX = this.rightleg.rotateAngleX + 0.4363323F;
		this.leftfootlower.rotateAngleX = this.leftleg.rotateAngleX + 0.4363323F;
		this.rightleg.rotateAngleX -= 0.3490659F;
		this.leftleg.rotateAngleX -= 0.3490659F;
		
        float f6;
        float f7;

        if (this.onGround > -9990.0F)
        {
            f6 = this.onGround;
            f6 = 1.0F - this.onGround;
            f6 *= f6;
            f6 *= f6;
            f6 = 1.0F - f6;
            f7 = MathHelper.sin(f6 * (float)Math.PI);
            float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
            
            this.righthand.rotateAngleX = (float)((double)this.righthand.rotateAngleX - ((double)f7 * 1.2D + (double)f8)) - 0.1745329F;
            this.rightarm.rotateAngleX = this.righthand.rotateAngleX;
            this.rightarmlower.rotateAngleX = this.righthand.rotateAngleX;
            
            this.lefthand.rotateAngleX = (float)((double)this.lefthand.rotateAngleX - ((double)f7 * 1.2D + (double)f8)) - 0.1745329F;
            this.leftarm.rotateAngleX = this.lefthand.rotateAngleX;
            this.leftarmlower.rotateAngleX = this.lefthand.rotateAngleX;
            
            this.righthand.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.rightarm.rotateAngleY = this.righthand.rotateAngleY;
            this.rightarmlower.rotateAngleY = this.righthand.rotateAngleY;
            
            this.lefthand.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.leftarm.rotateAngleY = this.lefthand.rotateAngleY;
            this.leftarmlower.rotateAngleY = this.lefthand.rotateAngleY;
            
            this.righthand.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F);
            this.rightarm.rotateAngleZ = this.righthand.rotateAngleZ + 0.1745329F;
            this.rightarmlower.rotateAngleZ = this.righthand.rotateAngleZ + 0.1745329F;
            this.righthand.rotateAngleZ = this.righthand.rotateAngleZ + 0.0872665F;
            
            this.lefthand.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F);
            this.leftarm.rotateAngleZ = this.lefthand.rotateAngleZ - 0.1745329F;
            this.leftarmlower.rotateAngleZ = this.lefthand.rotateAngleZ - 0.1745329F;
            this.lefthand.rotateAngleZ = this.lefthand.rotateAngleZ - 0.0872665F;
        }
	}
}
