package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaWitch extends ModelBase {
	ModelRenderer bodytop;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer bodymiddle;
	ModelRenderer hat1;
	ModelRenderer hat2;
	ModelRenderer hat3;
	ModelRenderer hat4;
	ModelRenderer hat5;
	ModelRenderer hat6;
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer mantle1;
	ModelRenderer mantle2;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	public static ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer broom;
	ModelRenderer broomstick;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer leftleglower;
	ModelRenderer rightleglower;
	ModelRenderer skirt1;
	ModelRenderer skirt2;

	public ModelGaiaWitch() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -1.5F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, 1F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, 0.4363323F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -0.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0.3490659F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -1F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.3490659F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -0.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0.3490659F, 0F, 0F);
		this.hat1 = new ModelRenderer(this, 36, 14);
		this.hat1.addBox(-7F, -7F, -7F, 14, 2, 14);
		this.hat1.setRotationPoint(0F, 1F, 0F);
		this.hat1.setTextureSize(64, 32);
		this.hat1.mirror = true;
		this.setRotation(hat1, 0F, 0.6108652F, 0F);
		this.hat2 = new ModelRenderer(this, 36, 30);
		this.hat2.addBox(-4F, -9F, -4F, 8, 2, 8);
		this.hat2.setRotationPoint(0F, 1F, 0F);
		this.hat2.setTextureSize(64, 32);
		this.hat2.mirror = true;
		this.setRotation(hat2, 0F, 0.7853982F, 0F);
		this.hat3 = new ModelRenderer(this, 36, 40);
		this.hat3.addBox(-3F, -10F, -3F, 6, 1, 6);
		this.hat3.setRotationPoint(0F, 1F, 0F);
		this.hat3.setTextureSize(64, 32);
		this.hat3.mirror = true;
		this.setRotation(hat3, 0F, 0.9599311F, 0F);
		this.hat4 = new ModelRenderer(this, 36, 47);
		this.hat4.addBox(-2F, -11F, -2F, 4, 1, 4);
		this.hat4.setRotationPoint(0F, 1F, 0F);
		this.hat4.setTextureSize(64, 32);
		this.hat4.mirror = true;
		this.setRotation(hat4, 0F, 1.134464F, 0F);
		this.hat5 = new ModelRenderer(this, 36, 52);
		this.hat5.addBox(-1.5F, -12F, -1.5F, 3, 1, 3);
		this.hat5.setRotationPoint(0F, 1F, 0F);
		this.hat5.setTextureSize(64, 32);
		this.hat5.mirror = true;
		this.setRotation(hat5, 0F, 1.308997F, 0F);
		this.hat6 = new ModelRenderer(this, 36, 56);
		this.hat6.addBox(-1F, -14F, -1F, 2, 2, 2);
		this.hat6.setRotationPoint(0F, 1F, 0F);
		this.hat6.setTextureSize(64, 32);
		this.hat6.mirror = true;
		this.setRotation(hat6, 0F, 1.48353F, 0F);
		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, 0F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -7F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, 0F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.mantle1 = new ModelRenderer(this, 92, 0);
		this.mantle1.addBox(-5F, -1F, -1.5F, 10, 6, 3);
		this.mantle1.setRotationPoint(0F, 1F, 0F);
		this.mantle1.setTextureSize(64, 32);
		this.mantle1.mirror = true;
		this.setRotation(mantle1, 0.8726646F, 0F, 0F);
		this.mantle2 = new ModelRenderer(this, 92, 9);
		this.mantle2.addBox(-4.5F, 2F, -1F, 9, 10, 3);
		this.mantle2.setRotationPoint(0F, 1F, 0F);
		this.mantle2.setTextureSize(64, 32);
		this.mantle2.mirror = true;
		this.setRotation(mantle2, 0.6108652F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, 3F, -0.5F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 1.22173F, -0.1745329F, 0F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, 3F, -0.5F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 1.22173F, 0.1745329F, 0F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, -0.5235988F, -0.3490659F, 0F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, -0.5235988F, 0.3490659F, 0F);
		this.broom = new ModelRenderer(this, 92, 40);
		this.broom.addBox(0F, 6.5F, -2.5F, 3, 10, 3);
		this.broom.setRotationPoint(-1.5F, 10F, 4F);
		this.broom.setTextureSize(64, 32);
		this.broom.mirror = true;
		this.setRotation(broom, 1.570796F, 0F, 0F);
		this.broomstick = new ModelRenderer(this, 118, 0);
		this.broomstick.addBox(1F, -12.5F, -1.5F, 1, 26, 1);
		this.broomstick.setRotationPoint(-1.5F, 10F, 4F);
		this.broomstick.setTextureSize(64, 32);
		this.broomstick.mirror = true;
		this.setRotation(broomstick, 1.570796F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 24, 20);
		this.rightleg.addBox(-1F, 1F, -6F, 2, 4, 2);
		this.rightleg.setRotationPoint(-1.5F, 10F, 4F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, 0.6108652F, 0F, -0.0872665F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1F, 0F, -1F, 2, 6, 2);
		this.leftleg.setRotationPoint(1.5F, 10F, 4F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, -0.6981317F, 0F, 0.0872665F);
		this.leftleglower = new ModelRenderer(this, 24, 20);
		this.leftleglower.addBox(-1F, 1F, -6F, 2, 4, 2);
		this.leftleglower.setRotationPoint(1.5F, 10F, 4F);
		this.leftleglower.setTextureSize(64, 32);
		this.leftleglower.mirror = true;
		this.setRotation(leftleglower, 0.8726646F, 0F, 0.0872665F);
		this.rightleglower = new ModelRenderer(this, 24, 12);
		this.rightleglower.addBox(-1F, 0F, -1F, 2, 6, 2);
		this.rightleglower.setRotationPoint(-1.5F, 10F, 4F);
		this.rightleglower.setTextureSize(64, 32);
		this.rightleglower.mirror = true;
		this.setRotation(rightleglower, -0.9599311F, 0F, -0.0872665F);
		this.skirt1 = new ModelRenderer(this, 92, 22);
		this.skirt1.addBox(-3F, -1F, -2F, 6, 4, 4);
		this.skirt1.setRotationPoint(0F, 10F, 4F);
		this.skirt1.setTextureSize(64, 32);
		this.skirt1.mirror = true;
		this.setRotation(skirt1, 0.2617994F, 0F, 0F);
		this.skirt2 = new ModelRenderer(this, 92, 30);
		this.skirt2.addBox(-3.5F, 2F, -2F, 7, 5, 5);
		this.skirt2.setRotationPoint(0F, 10F, 4F);
		this.skirt2.setTextureSize(64, 32);
		this.skirt2.mirror = true;
		this.setRotation(skirt2, 0.0872665F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.bodytop.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.bodymiddle.render(par7);
		this.hat1.render(par7);
		this.hat2.render(par7);
		this.hat3.render(par7);
		this.hat4.render(par7);
		this.hat5.render(par7);
		this.hat6.render(par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.mantle1.render(par7);
		this.mantle2.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.rightarm.render(par7);
		this.leftarm.render(par7);
		this.broom.render(par7);
		this.broomstick.render(par7);
		this.rightleg.render(par7);
		this.leftleg.render(par7);
		this.leftleglower.render(par7);
		this.rightleglower.render(par7);
		this.skirt1.render(par7);
		this.skirt2.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.hat1.rotateAngleY = this.head.rotateAngleY + 0.6108652F;
		this.hat1.rotateAngleX = this.head.rotateAngleX;
		this.hat2.rotateAngleY = this.head.rotateAngleY + 0.7853982F;
		this.hat2.rotateAngleX = this.head.rotateAngleX;
		this.hat3.rotateAngleY = this.head.rotateAngleY + 0.9599311F;
		this.hat3.rotateAngleX = this.head.rotateAngleX;
		this.hat4.rotateAngleY = this.head.rotateAngleY + 1.134464F;
		this.hat4.rotateAngleX = this.head.rotateAngleX;
		this.hat5.rotateAngleY = this.head.rotateAngleY + 1.308997F;
		this.hat5.rotateAngleX = this.head.rotateAngleX;
		this.hat6.rotateAngleY = this.head.rotateAngleY + 1.48353F;
		this.hat6.rotateAngleX = this.head.rotateAngleX;
	}
}
