package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaFutakuchiOnna extends ModelBase{
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer hair1;
	ModelRenderer hair2;
	ModelRenderer hair3;
	ModelRenderer mouth1;
	ModelRenderer mouth2;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	ModelRenderer back;
	ModelRenderer rightarm;
	ModelRenderer rightarmupper;
	ModelRenderer leftarm;
	ModelRenderer leftarmupper;
	ModelRenderer waist;
	ModelRenderer rightleg;
	ModelRenderer rightsandal;
	ModelRenderer leftleg;
	ModelRenderer leftsandal;

	public ModelGaiaFutakuchiOnna() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, 2F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, -0.2617994F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, 2F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, -0.2617994F, 0F, 0F);
		this.hair1 = new ModelRenderer(this, 36, 14);
		this.hair1.addBox(-5F, -8F, -5.5F, 10, 10, 4);
		this.hair1.setRotationPoint(0F, 1F, 2F);
		this.hair1.setTextureSize(64, 32);
		this.hair1.mirror = true;
		this.setRotation(hair1, -0.0872665F, 0F, 0F);
		this.hair2 = new ModelRenderer(this, 36, 28);
		this.hair2.addBox(-4F, -7F, -7.5F, 8, 8, 4);
		this.hair2.setRotationPoint(0F, 1F, 2F);
		this.hair2.setTextureSize(64, 32);
		this.hair2.mirror = true;
		this.setRotation(hair2, -0.0872665F, 0F, 0F);
		this.hair3 = new ModelRenderer(this, 36, 40);
		this.hair3.addBox(-4F, -6F, -1F, 8, 10, 6);
		this.hair3.setRotationPoint(0F, 1F, 2F);
		this.hair3.setTextureSize(64, 32);
		this.hair3.mirror = true;
		this.setRotation(hair3, 0F, 0F, 0F);
		this.mouth1 = new ModelRenderer(this, 64, 0);
		this.mouth1.addBox(-3F, -3.5F, -6F, 6, 3, 6);
		this.mouth1.setRotationPoint(0F, -2F, 0.5F);
		this.mouth1.setTextureSize(64, 32);
		this.mouth1.mirror = true;
		this.setRotation(mouth1, 0F, 0F, 0F);
		this.mouth2 = new ModelRenderer(this, 64, 9);
		this.mouth2.addBox(-3F, -0.5F, -6F, 6, 3, 6);
		this.mouth2.setRotationPoint(0F, -2F, 0.5F);
		this.mouth2.setTextureSize(64, 32);
		this.mouth2.mirror = true;
		this.setRotation(mouth2, 0F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, 0F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, 1F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, -0.2443461F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, 0.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, -0.1745329F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -1.5F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(1.3F, 4F, 3F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, -0.9599311F, 0.1745329F, -0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(-1.3F, 4F, 3F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, -0.9599311F, -0.1745329F, 0.0872665F);
		this.back = new ModelRenderer(this, 88, 11);
		this.back.addBox(-3.5F, 4F, -1F, 7, 4, 1);
		this.back.setRotationPoint(0F, 1F, 0F);
		this.back.setTextureSize(64, 32);
		this.back.mirror = true;
		this.setRotation(back, -0.1745329F, 0F, 0F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, 2F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, 0F, 0F, 0.1745329F);
		this.rightarmupper = new ModelRenderer(this, 88, 0);
		this.rightarmupper.addBox(-2.5F, 0.5F, -1.5F, 3, 8, 3);
		this.rightarmupper.setRotationPoint(-2.5F, 2.5F, 2F);
		this.rightarmupper.setTextureSize(64, 32);
		this.rightarmupper.mirror = true;
		this.setRotation(rightarmupper, 0F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, 2F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, 0F, 0F, -0.1745329F);
		this.leftarmupper = new ModelRenderer(this, 100, 0);
		this.leftarmupper.addBox(-0.5F, 0.5F, -1.5F, 3, 8, 3);
		this.leftarmupper.setRotationPoint(2.5F, 2.5F, 2F);
		this.leftarmupper.setTextureSize(64, 32);
		this.leftarmupper.mirror = true;
		this.setRotation(leftarmupper, 0F, 0F, -0.1745329F);
		this.waist = new ModelRenderer(this, 88, 16);
		this.waist.addBox(-3F, 10F, -1F, 6, 3, 4);
		this.waist.setRotationPoint(0F, 1F, 0F);
		this.waist.setTextureSize(64, 32);
		this.waist.mirror = true;
		this.setRotation(waist, -0.0872665F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 24, 12);
		this.rightleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.rightleg.setRotationPoint(-1.5F, 11F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, 0F, 0F, 0F);
		this.rightsandal = new ModelRenderer(this, 88, 23);
		this.rightsandal.addBox(-1F, 11F, -1.5F, 2, 1, 3);
		this.rightsandal.setRotationPoint(-1.5F, 11F, 0F);
		this.rightsandal.setTextureSize(64, 32);
		this.rightsandal.mirror = true;
		this.setRotation(rightsandal, 0F, 0F, 0F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.leftleg.setRotationPoint(1.5F, 11F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, 0F, 0F, 0F);
		this.leftsandal = new ModelRenderer(this, 88, 23);
		this.leftsandal.addBox(-1F, 11F, -1.5F, 2, 1, 3);
		this.leftsandal.setRotationPoint(1.5F, 11F, 0F);
		this.leftsandal.setTextureSize(64, 32);
		this.leftsandal.mirror = true;
		this.setRotation(leftsandal, 0F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.hair1.render(par7);
		this.hair2.render(par7);
		this.hair3.render(par7);
		this.mouth1.render(par7);
		this.mouth2.render(par7);
		this.bodytop.render(par7);
		this.bodymiddle.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.back.render(par7);
		this.rightarm.render(par7);
		this.rightarmupper.render(par7);
		this.leftarm.render(par7);
		this.leftarmupper.render(par7);
		this.waist.render(par7);
		this.rightleg.render(par7);
		this.rightsandal.render(par7);
		this.leftleg.render(par7);
		this.leftsandal.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.hair1.rotateAngleY = this.head.rotateAngleY;
		this.hair2.rotateAngleY = this.head.rotateAngleY;
		this.hair3.rotateAngleY = this.head.rotateAngleY;
		this.mouth1.rotateAngleX = MathHelper.cos(par3 * 0.8F + (float)Math.PI) * 0.6F * par2 * 0.5F;
		this.mouth2.rotateAngleX = MathHelper.cos(par3 * 0.8F) * 0.6F * par2 * 0.5F;
		this.mouth1.rotateAngleY = this.head.rotateAngleY;
		this.mouth2.rotateAngleY = this.head.rotateAngleY;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.4F * par2 * 0.5F;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.4F * par2 * 0.5F;
		this.rightarmupper.rotateAngleX = this.rightarm.rotateAngleX;
		this.leftarmupper.rotateAngleX = this.leftarm.rotateAngleX;
		this.rightchest.rotateAngleX = this.rightleg.rotateAngleX - 0.9599311F;
		this.leftchest.rotateAngleX = this.rightleg.rotateAngleX - 0.9599311F;
		this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2;
		this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2;
		this.rightsandal.rotateAngleX = this.rightleg.rotateAngleX;
		this.leftsandal.rotateAngleX = this.leftleg.rotateAngleX;
	}
}
