package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaDhampir extends ModelBase {
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer hat01;
	ModelRenderer hat02;
	ModelRenderer hat03;
	ModelRenderer hatflower;
	ModelRenderer hair;
	ModelRenderer righthair;
	ModelRenderer lefthair;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer mantle;
	ModelRenderer cape01;
	ModelRenderer cape02;
	ModelRenderer waist;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	ModelRenderer rightpauldron;
	ModelRenderer leftpauldron;
	public static ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer rightboot;
	ModelRenderer leftboot;

	public ModelGaiaDhampir() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, 0F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, 0F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.hat01 = new ModelRenderer(this, 36, 33);
		this.hat01.addBox(-6F, -7F, -6F, 12, 2, 12);
		this.hat01.setRotationPoint(0F, 1F, 0F);
		this.hat01.setTextureSize(64, 32);
		this.hat01.mirror = true;
		this.setRotation(hat01, 0.0349066F, 0.9599311F, 0.0349066F);
		this.hat02 = new ModelRenderer(this, 36, 47);
		this.hat02.addBox(-3F, -10F, -3F, 6, 3, 6);
		this.hat02.setRotationPoint(0F, 1F, 0F);
		this.hat02.setTextureSize(64, 32);
		this.hat02.mirror = true;
		this.setRotation(hat02, 0.0349066F, 0.7853982F, 0.0349066F);
		this.hat03 = new ModelRenderer(this, 36, 56);
		this.hat03.addBox(-4F, -11F, 0F, 4, 3, 4);
		this.hat03.setRotationPoint(0F, 1F, 0F);
		this.hat03.setTextureSize(64, 32);
		this.hat03.mirror = true;
		this.setRotation(hat03, 0.0349066F, 0.9599311F, 0.0349066F);
		this.hatflower = new ModelRenderer(this, 84, 0);
		this.hatflower.addBox(-3.5F, -11F, -3.5F, 7, 4, 7);
		this.hatflower.setRotationPoint(0F, 1F, 0F);
		this.hatflower.setTextureSize(64, 32);
		this.hatflower.mirror = true;
		this.setRotation(hatflower, 0.0349066F, 0.7853982F, 0.0349066F);
		this.hair = new ModelRenderer(this, 36, 14);
		this.hair.addBox(-1F, -2.5F, 2.5F, 2, 12, 2);
		this.hair.setRotationPoint(0F, 1F, 0F);
		this.hair.setTextureSize(64, 32);
		this.hair.mirror = true;
		this.setRotation(hair, 0.3490659F, 0F, 0F);
		this.righthair = new ModelRenderer(this, 36, 28);
		this.righthair.addBox(-5F, -5F, -4F, 4, 4, 1);
		this.righthair.setRotationPoint(0F, 1F, 0F);
		this.righthair.setTextureSize(64, 32);
		this.righthair.mirror = true;
		this.setRotation(righthair, 0F, 0.7853982F, 0F);
		this.lefthair = new ModelRenderer(this, 46, 28);
		this.lefthair.addBox(1F, -5F, -4F, 4, 4, 1);
		this.lefthair.setRotationPoint(0F, 1F, 0F);
		this.lefthair.setTextureSize(64, 32);
		this.lefthair.mirror = true;
		this.setRotation(lefthair, 0F, -0.7853982F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -1.5F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, 1F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, -0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -1.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -2.5F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.0872665F, 0F, 0F);
		this.mantle = new ModelRenderer(this, 84, 11);
		this.mantle.addBox(-4F, -3F, -2F, 8, 4, 4);
		this.mantle.setRotationPoint(0F, 1F, 0F);
		this.mantle.setTextureSize(64, 32);
		this.mantle.mirror = true;
		this.setRotation(mantle, 0F, 0F, 0F);
		this.cape01 = new ModelRenderer(this, 84, 25);
		this.cape01.addBox(-5F, 1F, -1F, 10, 6, 3);
		this.cape01.setRotationPoint(0F, 1F, 0F);
		this.cape01.setTextureSize(64, 32);
		this.cape01.mirror = true;
		this.setRotation(cape01, 0.3490659F, 0F, 0F);
		this.cape02 = new ModelRenderer(this, 84, 34);
		this.cape02.addBox(-5.5F, 6F, 0.5F, 11, 6, 3);
		this.cape02.setRotationPoint(0F, 1F, 0F);
		this.cape02.setTextureSize(64, 32);
		this.cape02.mirror = true;
		this.setRotation(cape02, 0.1745329F, 0F, 0F);
		this.waist = new ModelRenderer(this, 84, 43);
		this.waist.addBox(-2.966667F, 7F, -2F, 6, 6, 4);
		this.waist.setRotationPoint(0F, 1F, 0F);
		this.waist.setTextureSize(64, 32);
		this.waist.mirror = true;
		this.setRotation(waist, 0F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, 3F, -1.5F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, 3F, -1.5F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 0.7853982F, -0.1570796F, -0.0872665F);
		this.rightpauldron = new ModelRenderer(this, 84, 19);
		this.rightpauldron.addBox(-2.5F, -1F, -1.5F, 3, 3, 3);
		this.rightpauldron.setRotationPoint(-2.5F, 2F, 0F);
		this.rightpauldron.setTextureSize(64, 32);
		this.rightpauldron.mirror = true;
		this.setRotation(rightpauldron, 0F, 0F, 0F);
		this.leftpauldron = new ModelRenderer(this, 96, 19);
		this.leftpauldron.addBox(-0.5F, -1.5F, -1.5F, 3, 3, 3);
		this.leftpauldron.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftpauldron.setTextureSize(64, 32);
		this.leftpauldron.mirror = true;
		this.setRotation(leftpauldron, 0F, 0F, 0F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, 0F, 0F, 0.0872665F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, 0F, 0F, -0.0872665F);
		this.rightleg = new ModelRenderer(this, 24, 12);
		this.rightleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.rightleg.setRotationPoint(-1.5F, 11F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, 0F, 0F, 0F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.leftleg.setRotationPoint(1.5F, 11F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, 0F, 0F, 0F);
		this.rightboot = new ModelRenderer(this, 84, 53);
		this.rightboot.addBox(-1.5F, 4F, -1.5F, 3, 7, 3);
		this.rightboot.setRotationPoint(-1.5F, 11F, 0F);
		this.rightboot.setTextureSize(64, 32);
		this.rightboot.mirror = true;
		this.setRotation(rightboot, 0F, 0F, 0F);
		this.leftboot = new ModelRenderer(this, 84, 53);
		this.leftboot.addBox(-1.5F, 4F, -1.5F, 3, 7, 3);
		this.leftboot.setRotationPoint(1.5F, 11F, 0F);
		this.leftboot.setTextureSize(64, 32);
		this.leftboot.mirror = true;
		this.setRotation(leftboot, 0F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.hat01.render(par7);
		this.hat02.render(par7);
		this.hat03.render(par7);
		this.hatflower.render(par7);
		this.hair.render(par7);
		this.righthair.render(par7);
		this.lefthair.render(par7);
		this.bodytop.render(par7);
		this.bodymiddle.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.mantle.render(par7);
		this.cape01.render(par7);
		this.cape02.render(par7);
		this.waist.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.rightpauldron.render(par7);
		this.leftpauldron.render(par7);
		this.rightarm.render(par7);
		this.leftarm.render(par7);
		this.rightleg.render(par7);
		this.leftleg.render(par7);
		this.rightboot.render(par7);
		this.leftboot.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.hat01.rotateAngleY = this.head.rotateAngleY + 0.9599311F;
		this.hat01.rotateAngleX = this.head.rotateAngleX + 0.0349066F;
		this.hat02.rotateAngleY = this.head.rotateAngleY + 0.7853982F;
		this.hat02.rotateAngleX = this.head.rotateAngleX + 0.0349066F;
		this.hat03.rotateAngleY = this.head.rotateAngleY + 0.9599311F;
		this.hat03.rotateAngleX = this.head.rotateAngleX + 0.0349066F;
		this.hatflower.rotateAngleY = this.head.rotateAngleY + 0.7853982F;
		this.hatflower.rotateAngleX = this.head.rotateAngleX + 0.0349066F;
		this.hair.rotateAngleY = this.head.rotateAngleY;
		this.righthair.rotateAngleY = this.head.rotateAngleY + 0.7853982F;
		this.righthair.rotateAngleX = this.head.rotateAngleX;
		this.lefthair.rotateAngleY = this.head.rotateAngleY - 0.7853982F;
		this.lefthair.rotateAngleX = this.head.rotateAngleX;
		this.mantle.rotateAngleY = this.head.rotateAngleY;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2 * 0.5F;
		this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2 * 0.5F;
		this.leftpauldron.rotateAngleX = this.leftarm.rotateAngleX;
		this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2;
		this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2;
		this.rightboot.rotateAngleX = this.rightleg.rotateAngleX;
		this.leftboot.rotateAngleX = this.leftleg.rotateAngleX;
		
        float f6;
        float f7;

        if (this.onGround > -9990.0F)
        {
            f6 = this.onGround;
            f6 = 1.0F - this.onGround;
            f6 *= f6;
            f6 *= f6;
            f6 = 1.0F - f6;
            f7 = MathHelper.sin(f6 * (float)Math.PI);
            float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
            
            this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)f7 * 1.2D + (double)f8));
            this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX;
            this.rightarm.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.rightpauldron.rotateAngleY = this.rightarm.rotateAngleY;
            this.rightarm.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F);
            this.rightpauldron.rotateAngleZ = this.rightarm.rotateAngleZ;
            this.rightarm.rotateAngleZ = this.rightarm.rotateAngleZ + 0.0872665F;
        }
	}
}
