package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaCentaur extends ModelBase {
    ModelRenderer head;
    ModelRenderer headaccessory;
    ModelRenderer rightear;
    ModelRenderer leftear;
    ModelRenderer hair1;
    ModelRenderer hair2;
    ModelRenderer bodytop;
    ModelRenderer bodymiddle;
    ModelRenderer bodymiddlebutton;
    ModelRenderer bodybottom;
    ModelRenderer rightchest;
    ModelRenderer leftchest;
    ModelRenderer rightpauldron;
	public static ModelRenderer rightarm;
    ModelRenderer rightarmguard;
    ModelRenderer leftarm;
    ModelRenderer front;
    ModelRenderer body1;
    ModelRenderer body2;
    ModelRenderer saddle;
    ModelRenderer saddle1;
    ModelRenderer saddle2;
    ModelRenderer rightsaddlestrap1;
    ModelRenderer rightsaddlestrap2;
    ModelRenderer leftsaddlestrap1;
    ModelRenderer leftsaddlestrap2;
    ModelRenderer rightlegupper;
    ModelRenderer rightleglower;
    ModelRenderer rightlegback1;
    ModelRenderer rightlegback2;
    ModelRenderer rightlegback3;
    ModelRenderer leftlegupper;
    ModelRenderer leftleglower;
    ModelRenderer leftlegback1;
    ModelRenderer leftlegback2;
    ModelRenderer leftlegback3;
    ModelRenderer tail;

	public ModelGaiaCentaur() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, -6F, -7.5F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, -6F, -7.5F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.rightear = new ModelRenderer(this, 36, 33);
		this.rightear.addBox(-4F, -5F, -1F, 0, 4, 4);
		this.rightear.setRotationPoint(0F, -6F, -7.5F);
		this.rightear.setTextureSize(64, 32);
		this.rightear.mirror = true;
		this.setRotation(rightear, 0F, -0.5235988F, 0F);
		this.leftear = new ModelRenderer(this, 36, 33);
		this.leftear.addBox(4F, -5F, -1F, 0, 4, 4);
		this.leftear.setRotationPoint(0F, -6F, -7.5F);
		this.leftear.setTextureSize(64, 32);
		this.leftear.mirror = true;
		this.setRotation(leftear, 0F, 0.5235988F, 0F);
		this.hair1 = new ModelRenderer(this, 36, 14);
		this.hair1.addBox(-4F, -6F, 1F, 8, 8, 3);
		this.hair1.setRotationPoint(0F, -6F, -7.5F);
		this.hair1.setTextureSize(64, 32);
		this.hair1.mirror = true;
		this.setRotation(hair1, 0F, 0F, 0F);
		this.hair2 = new ModelRenderer(this, 36, 25);
		this.hair2.addBox(-4.5F, -1F, 1.5F, 9, 9, 3);
		this.hair2.setRotationPoint(0F, -6F, -7.5F);
		this.hair2.setTextureSize(64, 32);
		this.hair2.mirror = true;
		this.setRotation(hair2, 0F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -2F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, -6F, -7F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, -0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -2F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, -6F, -7F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 4.5F, -2.1F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, -5.5F, -7F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -3F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, -6F, -7F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.0872665F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, -4F, -9F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, -4F, -9F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 0.7853982F, -0.1745329F, -0.0872665F);
		this.rightpauldron = new ModelRenderer(this, 36, 41);
		this.rightpauldron.addBox(-3F, -1.5F, -2F, 4, 3, 4);
		this.rightpauldron.setRotationPoint(-2.5F, -5F, -7.5F);
		this.rightpauldron.setTextureSize(64, 32);
		this.rightpauldron.mirror = true;
		this.setRotation(rightpauldron, 0F, 0F, 0.1745329F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, -5F, -7.5F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, 0F, 0F, 0.1745329F);
		this.rightarmguard = new ModelRenderer(this, 16, 36);
		this.rightarmguard.addBox(-2.5F, 3F, -1.5F, 3, 4, 3);
		this.rightarmguard.setRotationPoint(-2.5F, -5F, -7.5F);
		this.rightarmguard.setTextureSize(64, 32);
		this.rightarmguard.mirror = true;
		this.setRotation(rightarmguard, 0F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 24);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, -5F, -7.5F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, 0F, 0F, -0.0872665F);
		this.front = new ModelRenderer(this, 36, 48);
		this.front.addBox(-3F, 9F, -2F, 6, 10, 3);
		this.front.setRotationPoint(0F, -6F, -7F);
		this.front.setTextureSize(64, 32);
		this.front.mirror = true;
		this.setRotation(front, -0.0872665F, 0F, 0F);
		this.body1 = new ModelRenderer(this, 64, 26);
		this.body1.addBox(-4F, 14F, 0F, 8, 9, 9);
		this.body1.setRotationPoint(0F, -10F, -8F);
		this.body1.setTextureSize(64, 32);
		this.body1.mirror = true;
		this.setRotation(body1, -0.0872665F, 0F, 0F);
		this.body2 = new ModelRenderer(this, 64, 44);
		this.body2.addBox(-3.5F, 15.5F, 5F, 7, 8, 12);
		this.body2.setRotationPoint(0F, -10F, -8F);
		this.body2.setTextureSize(64, 32);
		this.body2.mirror = true;
		this.setRotation(body2, 0.0872665F, 0F, 0F);
		this.saddle = new ModelRenderer(this, 64, 0);
		this.saddle.addBox(-4F, 13.5F, 5F, 8, 1, 8);
		this.saddle.setRotationPoint(0F, -10F, -8F);
		this.saddle.setTextureSize(64, 32);
		this.saddle.mirror = true;
		this.setRotation(saddle, 0F, 0F, 0F);
		this.saddle1 = new ModelRenderer(this, 64, 9);
		this.saddle1.addBox(-1F, 12.5F, 5F, 2, 1, 2);
		this.saddle1.setRotationPoint(0F, -10F, -8F);
		this.saddle1.setTextureSize(64, 32);
		this.saddle1.mirror = true;
		this.setRotation(saddle1, 0F, 0F, 0F);
		this.saddle2 = new ModelRenderer(this, 64, 12);
		this.saddle2.addBox(-3F, 12.5F, 11F, 6, 1, 2);
		this.saddle2.setRotationPoint(0F, -10F, -8F);
		this.saddle2.setTextureSize(64, 32);
		this.saddle2.mirror = true;
		this.setRotation(saddle2, 0F, 0F, 0F);
		this.rightsaddlestrap1 = new ModelRenderer(this, 64, 15);
		this.rightsaddlestrap1.addBox(-0.5F, -0.5F, -0.5F, 1, 6, 1);
		this.rightsaddlestrap1.setRotationPoint(-4F, 4F, 0F);
		this.rightsaddlestrap1.setTextureSize(64, 32);
		this.rightsaddlestrap1.mirror = true;
		this.setRotation(rightsaddlestrap1, 0F, 0F, 0F);
		this.rightsaddlestrap2 = new ModelRenderer(this, 64, 22);
		this.rightsaddlestrap2.addBox(-0.5F, 5.5F, -1F, 1, 2, 2);
		this.rightsaddlestrap2.setRotationPoint(-4F, 4F, 0F);
		this.rightsaddlestrap2.setTextureSize(64, 32);
		this.rightsaddlestrap2.mirror = true;
		this.setRotation(rightsaddlestrap2, 0F, 0F, 0F);
		this.leftsaddlestrap1 = new ModelRenderer(this, 64, 15);
		this.leftsaddlestrap1.addBox(-0.5F, -0.5F, -0.5F, 1, 6, 1);
		this.leftsaddlestrap1.setRotationPoint(4F, 4F, 0F);
		this.leftsaddlestrap1.setTextureSize(64, 32);
		this.leftsaddlestrap1.mirror = true;
		this.setRotation(leftsaddlestrap1, 0F, 0F, 0F);
		this.leftsaddlestrap2 = new ModelRenderer(this, 64, 22);
		this.leftsaddlestrap2.addBox(-0.5F, 5.5F, -1F, 1, 2, 2);
		this.leftsaddlestrap2.setRotationPoint(4F, 4F, 0F);
		this.leftsaddlestrap2.setTextureSize(64, 32);
		this.leftsaddlestrap2.mirror = true;
		this.setRotation(leftsaddlestrap2, 0F, 0F, 0F);
		this.rightlegupper = new ModelRenderer(this, 102, 0);
		this.rightlegupper.addBox(-1.466667F, -1.5F, -1.5F, 3, 8, 3);
		this.rightlegupper.setRotationPoint(-4F, 9F, -7F);
		this.rightlegupper.setTextureSize(64, 32);
		this.rightlegupper.mirror = true;
		this.setRotation(rightlegupper, 0F, 0F, -0.0872665F);
		this.rightleglower = new ModelRenderer(this, 102, 11);
		this.rightleglower.addBox(-1F, 6.5F, -0.5F, 2, 8, 2);
		this.rightleglower.setRotationPoint(-4F, 9F, -7F);
		this.rightleglower.setTextureSize(64, 32);
		this.rightleglower.mirror = true;
		this.setRotation(rightleglower, 0F, 0F, -0.0872665F);
		this.rightlegback1 = new ModelRenderer(this, 102, 21);
		this.rightlegback1.addBox(-0.5F, -2.5F, -1.5F, 3, 8, 6);
		this.rightlegback1.setRotationPoint(-4F, 7F, 7F);
		this.rightlegback1.setTextureSize(64, 32);
		this.rightlegback1.mirror = true;
		this.setRotation(rightlegback1, -0.296706F, 0F, -0.0872665F);
		this.rightlegback2 = new ModelRenderer(this, 102, 35);
		this.rightlegback2.addBox(-1.5F, 2F, 2.5F, 3, 3, 6);
		this.rightlegback2.setRotationPoint(-4F, 7F, 7F);
		this.rightlegback2.setTextureSize(64, 32);
		this.rightlegback2.mirror = true;
		this.setRotation(rightlegback2, -1.047198F, 0F, -0.0872665F);
		this.rightlegback3 = new ModelRenderer(this, 102, 44);
		this.rightlegback3.addBox(-1F, 8F, 1.5F, 2, 8, 2);
		this.rightlegback3.setRotationPoint(-4F, 7F, 7F);
		this.rightlegback3.setTextureSize(64, 32);
		this.rightlegback3.mirror = true;
		this.setRotation(rightlegback3, -0.122173F, 0F, -0.0872665F);
		this.leftlegupper = new ModelRenderer(this, 102, 0);
		this.leftlegupper.addBox(-1.466667F, -1.5F, -1.5F, 3, 8, 3);
		this.leftlegupper.setRotationPoint(4F, 9F, -7F);
		this.leftlegupper.setTextureSize(64, 32);
		this.leftlegupper.mirror = true;
		this.setRotation(leftlegupper, 0F, 0F, 0.0872665F);
		this.leftleglower = new ModelRenderer(this, 102, 11);
		this.leftleglower.addBox(-1F, 6.5F, -0.5F, 2, 8, 2);
		this.leftleglower.setRotationPoint(4F, 9F, -7F);
		this.leftleglower.setTextureSize(64, 32);
		this.leftleglower.mirror = true;
		this.setRotation(leftleglower, 0F, 0F, 0.0872665F);
		this.leftlegback1 = new ModelRenderer(this, 102, 21);
		this.leftlegback1.addBox(-2.5F, -2.5F, -1.5F, 3, 8, 6);
		this.leftlegback1.setRotationPoint(4F, 7F, 7F);
		this.leftlegback1.setTextureSize(64, 32);
		this.leftlegback1.mirror = true;
		this.setRotation(leftlegback1, -0.296706F, 0F, 0.0872665F);
		this.leftlegback2 = new ModelRenderer(this, 102, 35);
		this.leftlegback2.addBox(-1.5F, 2F, 2.5F, 3, 3, 6);
		this.leftlegback2.setRotationPoint(4F, 7F, 7F);
		this.leftlegback2.setTextureSize(64, 32);
		this.leftlegback2.mirror = true;
		this.setRotation(leftlegback2, -1.047198F, 0F, 0.0872665F);
		this.leftlegback3 = new ModelRenderer(this, 102, 44);
		this.leftlegback3.addBox(-1F, 8F, 1.5F, 2, 8, 2);
		this.leftlegback3.setRotationPoint(4F, 7F, 7F);
		this.leftlegback3.setTextureSize(64, 32);
		this.leftlegback3.mirror = true;
		this.setRotation(leftlegback3, -0.122173F, 0F, 0.0872665F);
		this.tail = new ModelRenderer(this, 102, 54);
		this.tail.addBox(-1F, -1F, -0.5F, 2, 2, 8);
		this.tail.setRotationPoint(0F, 6F, 8F);
		this.tail.setTextureSize(64, 32);
		this.tail.mirror = true;
		this.setRotation(tail, -1.047198F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
	    this.head.render(par7);
	    this.headaccessory.render(par7);
	    this.rightear.render(par7);
	    this.leftear.render(par7);
	    this.hair1.render(par7);
	    this.hair2.render(par7);
	    this.bodytop.render(par7);
	    this.bodymiddle.render(par7);
	    this.bodymiddlebutton.render(par7);
	    this.bodybottom.render(par7);
	    this.rightchest.render(par7);
	    this.leftchest.render(par7);
	    this.rightpauldron.render(par7);
	    this.rightarm.render(par7);
	    this.rightarmguard.render(par7);
	    this.leftarm.render(par7);
	    this.front.render(par7);
	    this.body1.render(par7);
	    this.body2.render(par7);
	    this.saddle.render(par7);
	    this.saddle1.render(par7);
	    this.saddle2.render(par7);
	    this.rightsaddlestrap1.render(par7);
	    this.rightsaddlestrap2.render(par7);
	    this.leftsaddlestrap1.render(par7);
	    this.leftsaddlestrap2.render(par7);
	    this.rightlegupper.render(par7);
	    this.rightleglower.render(par7);
	    this.rightlegback1.render(par7);
	    this.rightlegback2.render(par7);
	    this.rightlegback3.render(par7);
	    this.leftlegupper.render(par7);
	    this.leftleglower.render(par7);
	    this.leftlegback1.render(par7);
	    this.leftlegback2.render(par7);
	    this.leftlegback3.render(par7);
	    this.tail.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.rightear.rotateAngleY = this.head.rotateAngleY - 0.5235988F;
		this.rightear.rotateAngleX = this.head.rotateAngleX;
		this.leftear.rotateAngleY = this.head.rotateAngleY + 0.5235988F;
		this.leftear.rotateAngleX = this.head.rotateAngleX;
		this.hair1.rotateAngleY = this.head.rotateAngleY;
		this.hair2.rotateAngleY = this.head.rotateAngleY;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.5F * par2 * 0.5F;
		this.rightarmguard.rotateAngleX = this.rightarm.rotateAngleX;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2 * 0.5F;
		this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX;
		this.rightlegupper.rotateAngleX = MathHelper.cos(par1 * 0.7862F) * 0.8F * par2;
		this.leftlegupper.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2;
		this.rightleglower.rotateAngleX = this.rightlegupper.rotateAngleX;
		this.leftleglower.rotateAngleX = this.leftlegupper.rotateAngleX;
		this.rightsaddlestrap1.rotateAngleX = MathHelper.cos(par1 * 0.7862F) * 0.4F * par2;
		this.rightsaddlestrap2.rotateAngleX = this.rightsaddlestrap1.rotateAngleX;
		this.leftsaddlestrap1.rotateAngleX = this.rightsaddlestrap1.rotateAngleX;
		this.leftsaddlestrap2.rotateAngleX = this.rightsaddlestrap1.rotateAngleX;
		this.tail.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.rightlegback1.rotateAngleX = MathHelper.cos(par1 * 0.7662F + (float)Math.PI) * 0.8F * par2;
		this.leftlegback1.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2;
		this.rightlegback2.rotateAngleX = this.rightlegback1.rotateAngleX - 1.047198F;
		this.leftlegback2.rotateAngleX = this.leftlegback1.rotateAngleX - 1.047198F;
		this.rightlegback3.rotateAngleX = this.rightlegback1.rotateAngleX - 0.122173F;
		this.leftlegback3.rotateAngleX = this.leftlegback1.rotateAngleX - 0.122173F;
		this.rightlegback1.rotateAngleX -= 0.296706F;
		this.leftlegback1.rotateAngleX -= 0.296706F;

        float f6;
        float f7;

        if (this.onGround > -9990.0F)
        {
            f6 = this.onGround;
            f6 = 1.0F - this.onGround;
            f6 *= f6;
            f6 *= f6;
            f6 = 1.0F - f6;
            f7 = MathHelper.sin(f6 * (float)Math.PI);
            float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
            
            this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)f7 * 1.2D + (double)f8));
            this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX; 
            this.rightarm.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.rightpauldron.rotateAngleY = this.rightarm.rotateAngleY; 
            this.rightarm.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F) + 0.1745329F;
            this.rightpauldron.rotateAngleZ = this.rightarm.rotateAngleZ; 
        }
	}
}
