package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaNPCTrader extends ModelBase {
	ModelRenderer bodytop;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodymiddle;
	ModelRenderer bodybottom;
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer righthair;
	ModelRenderer lefthair;
	ModelRenderer righthairpin;
	ModelRenderer leftthairpin;
	ModelRenderer rightear;
	ModelRenderer leftear;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightpauldron;
	ModelRenderer leftpauldron;
	ModelRenderer waist01;
	ModelRenderer waist02;
	ModelRenderer waist03;
	ModelRenderer bag;
	ModelRenderer watch;
	ModelRenderer rightleg;
	ModelRenderer leftleg;

	public ModelGaiaNPCTrader()
	{
		textureWidth = 128;
		textureHeight = 64;

		bodytop = new ModelRenderer(this, 0, 12);
		bodytop.addBox(-2.5F, 0F, -1.5F, 5, 5, 3);
		bodytop.setRotationPoint(0F, 1F, 0F);
		bodytop.setTextureSize(64, 32);
		bodytop.mirror = true;
		setRotation(bodytop, -0.0872665F, 0F, 0F);
		bodymiddlebutton = new ModelRenderer(this, 0, 20);
		bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		bodymiddlebutton.setTextureSize(64, 32);
		bodymiddlebutton.mirror = true;
		setRotation(bodymiddlebutton, 0F, 0F, 0F);
		bodymiddle = new ModelRenderer(this, 0, 20);
		bodymiddle.addBox(-2F, 4.5F, -1.5F, 4, 3, 2);
		bodymiddle.setRotationPoint(0F, 1F, 0F);
		bodymiddle.setTextureSize(64, 32);
		bodymiddle.mirror = true;
		setRotation(bodymiddle, 0F, 0F, 0F);
		bodybottom = new ModelRenderer(this, 0, 25);
		bodybottom.addBox(-2.5F, 7F, -2.5F, 5, 3, 3);
		bodybottom.setRotationPoint(0F, 1F, 0F);
		bodybottom.setTextureSize(64, 32);
		bodybottom.mirror = true;
		setRotation(bodybottom, 0.0872665F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-3F, -6F, -3F, 6, 6, 6);
		head.setRotationPoint(0F, 1F, 0F);
		head.setTextureSize(64, 32);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		headaccessory = new ModelRenderer(this, 36, 0);
		headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		headaccessory.setRotationPoint(0F, 1F, 0F);
		headaccessory.setTextureSize(64, 32);
		headaccessory.mirror = true;
		setRotation(headaccessory, 0F, 0F, 0F);
		righthair = new ModelRenderer(this, 36, 14);
		righthair.addBox(-5F, -5F, 1.5F, 3, 9, 3);
		righthair.setRotationPoint(0F, 1F, 0F);
		righthair.setTextureSize(64, 32);
		righthair.mirror = true;
		setRotation(righthair, 0F, 0.0872665F, 0.1745329F);
		lefthair = new ModelRenderer(this, 36, 14);
		lefthair.addBox(2F, -5F, 1.5F, 3, 9, 3);
		lefthair.setRotationPoint(0F, 1F, 0F);
		lefthair.setTextureSize(64, 32);
		lefthair.mirror = true;
		setRotation(lefthair, 0F, -0.0872665F, -0.1745329F);
		righthairpin = new ModelRenderer(this, 36, 26);
		righthairpin.addBox(-6F, -8F, 1F, 4, 4, 4);
		righthairpin.setRotationPoint(0F, 1F, 0F);
		righthairpin.setTextureSize(64, 32);
		righthairpin.mirror = true;
		setRotation(righthairpin, 0F, 0F, 0.1745329F);
		leftthairpin = new ModelRenderer(this, 52, 26);
		leftthairpin.addBox(2F, -8F, 1F, 4, 4, 4);
		leftthairpin.setRotationPoint(0F, 1F, 0F);
		leftthairpin.setTextureSize(64, 32);
		leftthairpin.mirror = true;
		setRotation(leftthairpin, 0F, 0F, -0.1745329F);
		rightear = new ModelRenderer(this, 36, 34);
		rightear.addBox(-3F, -8.5F, -6F, 2, 8, 6);
		rightear.setRotationPoint(0F, 1F, 0F);
		rightear.setTextureSize(64, 32);
		rightear.mirror = true;
		setRotation(rightear, 0F, 0.2617994F, 0F);
		leftear = new ModelRenderer(this, 36, 34);
		leftear.addBox(1F, -8.5F, -6F, 2, 8, 6);
		leftear.setRotationPoint(0F, 1F, 0F);
		leftear.setTextureSize(64, 32);
		leftear.mirror = true;
		setRotation(leftear, 0F, -0.2617994F, 0F);
		rightchest = new ModelRenderer(this, 0, 31);
		rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		rightchest.setRotationPoint(-1.3F, 3F, -1.5F);
		rightchest.setTextureSize(64, 32);
		rightchest.mirror = true;
		setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		leftchest = new ModelRenderer(this, 8, 31);
		leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		leftchest.setRotationPoint(1.3F, 3F, -1.5F);
		leftchest.setTextureSize(64, 32);
		leftchest.mirror = true;
		setRotation(leftchest, 0.7853982F, -0.1745329F, -0.0872665F);
		rightarm = new ModelRenderer(this, 16, 12);
		rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		rightarm.setRotationPoint(-2.5F, 2.5F, 0F);
		rightarm.setTextureSize(64, 32);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0.1745329F);
		leftarm = new ModelRenderer(this, 16, 12);
		leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		leftarm.setRotationPoint(2.5F, 2.5F, 0F);
		leftarm.setTextureSize(64, 32);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, -0.1745329F);
		rightpauldron = new ModelRenderer(this, 36, 48);
		rightpauldron.addBox(-2.5F, -1.5F, -1.5F, 3, 3, 3);
		rightpauldron.setRotationPoint(-2.5F, 2.5F, 0F);
		rightpauldron.setTextureSize(64, 32);
		rightpauldron.mirror = true;
		setRotation(rightpauldron, 0F, 0F, 0.1745329F);
		leftpauldron = new ModelRenderer(this, 48, 48);
		leftpauldron.addBox(-0.5F, -1.5F, -1.5F, 3, 3, 3);
		leftpauldron.setRotationPoint(2.5F, 2.5F, 0F);
		leftpauldron.setTextureSize(64, 32);
		leftpauldron.mirror = true;
		setRotation(leftpauldron, 0F, 0F, -0.1745329F);
		waist01 = new ModelRenderer(this, 68, 19);
		waist01.addBox(-3F, -2F, -2F, 6, 2, 4);
		waist01.setRotationPoint(0F, 11F, 0F);
		waist01.setTextureSize(64, 32);
		waist01.mirror = true;
		setRotation(waist01, 0F, 0F, 0F);
		waist02 = new ModelRenderer(this, 68, 25);
		waist02.addBox(-3.5F, 0F, -2.5F, 7, 3, 5);
		waist02.setRotationPoint(0F, 11F, 0F);
		waist02.setTextureSize(64, 32);
		waist02.mirror = true;
		setRotation(waist02, 0F, 0F, 0F);
		waist03 = new ModelRenderer(this, 68, 33);
		waist03.addBox(-4F, 3F, -3.5F, 8, 5, 7);
		waist03.setRotationPoint(0F, 11F, 0F);
		waist03.setTextureSize(64, 32);
		waist03.mirror = true;
		setRotation(waist03, 0F, 0F, 0F);
		bag = new ModelRenderer(this, 68, 0);
		bag.addBox(-3F, -2F, 0F, 6, 5, 4);
		bag.setRotationPoint(0F, 11F, 0F);
		bag.setTextureSize(64, 32);
		bag.mirror = true;
		setRotation(bag, 0.1745329F, 0F, 0F);
		watch = new ModelRenderer(this, 68, 9);
		watch.addBox(-4F, -2F, -2.5F, 1, 5, 5);
		watch.setRotationPoint(0F, 11F, 0F);
		watch.setTextureSize(64, 32);
		watch.mirror = true;
		setRotation(watch, 0F, 0F, 0.1745329F);
		rightleg = new ModelRenderer(this, 24, 12);
		rightleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		rightleg.setRotationPoint(-1.5F, 11F, 0F);
		rightleg.setTextureSize(64, 32);
		rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		leftleg = new ModelRenderer(this, 24, 12);
		leftleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		leftleg.setRotationPoint(1.5F, 11F, 0F);
		leftleg.setTextureSize(64, 32);
		leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		bodytop.render(par7);
		bodymiddlebutton.render(par7);
		bodymiddle.render(par7);
		bodybottom.render(par7);
		head.render(par7);
		headaccessory.render(par7);
		righthair.render(par7);
		lefthair.render(par7);
		righthairpin.render(par7);
		leftthairpin.render(par7);
		rightear.render(par7);
		leftear.render(par7);
		rightchest.render(par7);
		leftchest.render(par7);
		rightarm.render(par7);
		leftarm.render(par7);
		rightpauldron.render(par7);
		leftpauldron.render(par7);
		waist01.render(par7);
		waist02.render(par7);
		waist03.render(par7);
		bag.render(par7);
		watch.render(par7);
		rightleg.render(par7);
		leftleg.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.rightear.rotateAngleY = this.head.rotateAngleY + 0.2617994F;
		this.rightear.rotateAngleX = this.head.rotateAngleX;
		this.leftear.rotateAngleY = this.head.rotateAngleY - 0.2617994F;
		this.leftear.rotateAngleX = this.head.rotateAngleX;
		this.righthair.rotateAngleY = this.head.rotateAngleY + 0.0872665F;
		this.lefthair.rotateAngleY = this.head.rotateAngleY - 0.0872665F;
		this.righthairpin.rotateAngleY = this.head.rotateAngleY;
		this.leftthairpin.rotateAngleY = this.head.rotateAngleY;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2 * 0.5F;
		this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2 * 0.5F;
		this.leftpauldron.rotateAngleX = this.leftarm.rotateAngleX;
		this.bag.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.5F * par2;
		this.watch.rotateAngleX = this.leftleg.rotateAngleX;
	}
}
