package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaNineTails extends ModelBase {
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer hair1;
    ModelRenderer hair2;
	ModelRenderer rightear;
	ModelRenderer leftear;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer tie;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	public static ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightarmupper;
	ModelRenderer leftarmupper;
	ModelRenderer tail1;
	ModelRenderer tail2;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer rightlegcloth;
	ModelRenderer leftlegcloth;

	public ModelGaiaNineTails() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, 1F, 0F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, 1F, 0F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.hair1 = new ModelRenderer(this, 36, 14);
		this.hair1.addBox(-4F, -6F, 1F, 8, 8, 3);
		this.hair1.setRotationPoint(0F, 1F, 0F);
		this.hair1.setTextureSize(64, 32);
		this.hair1.mirror = true;
		this.setRotation(hair1, 0F, 0F, 0F);
		this.hair2 = new ModelRenderer(this, 36, 25);
		this.hair2.addBox(-4.5F, -1F, 1.5F, 9, 9, 3);
		this.hair2.setRotationPoint(0F, 1F, 0F);
		this.hair2.setTextureSize(64, 32);
		this.hair2.mirror = true;
		this.setRotation(hair2, 0F, 0F, 0F);
		this.rightear = new ModelRenderer(this, 36, 37);
		this.rightear.addBox(-4.5F, -10F, -1.5F, 3, 4, 3);
		this.rightear.setRotationPoint(0F, 1F, 0F);
		this.rightear.setTextureSize(64, 32);
		this.rightear.mirror = true;
		this.setRotation(rightear, 0F, 0F, 0F);
		this.leftear = new ModelRenderer(this, 48, 37);
		this.leftear.addBox(1.5F, -10F, -1.5F, 3, 4, 3);
		this.leftear.setRotationPoint(0F, 1F, 0F);
		this.leftear.setTextureSize(64, 32);
		this.leftear.mirror = true;
		this.setRotation(leftear, 0F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -1.5F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, 1F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, -0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -1.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, 1F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, 1F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -2.5F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, 1F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.0872665F, 0F, 0F);
		this.tie = new ModelRenderer(this, 36, 44);
		this.tie.addBox(-1.5F, 3F, -2.5F, 3, 2, 1);
		this.tie.setRotationPoint(0F, 1F, 0F);
		this.tie.setTextureSize(64, 32);
		this.tie.mirror = true;
		this.setRotation(tie, 0F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, 3F, -1.5F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, 3F, -1.5F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 0.7853982F, -0.1745329F, -0.0872665F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, 0F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, 0F, 0F, -0.1745329F);
		this.rightarmupper = new ModelRenderer(this, 36, 47);
		this.rightarmupper.addBox(-2.5F, -0.5F, -1.5F, 3, 9, 3);
		this.rightarmupper.setRotationPoint(-2.5F, 2.5F, 0F);
		this.rightarmupper.setTextureSize(64, 32);
		this.rightarmupper.mirror = true;
		this.setRotation(rightarmupper, 0F, 0F, 0.1745329F);
		this.leftarmupper = new ModelRenderer(this, 48, 47);
		this.leftarmupper.addBox(-0.5F, -0.5F, -1.5F, 3, 9, 3);
		this.leftarmupper.setRotationPoint(2.5F, 2.5F, 0F);
		this.leftarmupper.setTextureSize(64, 32);
		this.leftarmupper.mirror = true;
		this.setRotation(leftarmupper, 0F, 0F, -0.1745329F);
		this.tail1 = new ModelRenderer(this, 64, 0);
		this.tail1.addBox(-3.5F, 6.5F, 2F, 7, 7, 4);
		this.tail1.setRotationPoint(0F, 1F, 0F);
		this.tail1.setTextureSize(64, 32);
		this.tail1.mirror = true;
		this.setRotation(tail1, -0.0872665F, 0F, 0F);
		this.tail2 = new ModelRenderer(this, 64, 11);
		this.tail2.addBox(-2.5F, 7F, 6.5F, 5, 5, 4);
		this.tail2.setRotationPoint(0F, 1F, 0F);
		this.tail2.setTextureSize(64, 32);
		this.tail2.mirror = true;
		this.setRotation(tail2, -0.1745329F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 24, 12);
		this.rightleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.rightleg.setRotationPoint(-1.5F, 11F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, 0F, 0F, 0F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.leftleg.setRotationPoint(1.5F, 11F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, 0F, 0F, 0F);
		this.rightlegcloth = new ModelRenderer(this, 64, 20);
		this.rightlegcloth.addBox(-1.5F, 0F, -2F, 3, 12, 4);
		this.rightlegcloth.setRotationPoint(-1.5F, 11F, 0F);
		this.rightlegcloth.setTextureSize(64, 32);
		this.rightlegcloth.mirror = true;
		this.setRotation(rightlegcloth, 0F, 0F, 0F);
		this.leftlegcloth = new ModelRenderer(this, 78, 20);
		this.leftlegcloth.addBox(-1.5F, 0F, -2F, 3, 12, 4);
		this.leftlegcloth.setRotationPoint(1.5F, 11F, 0F);
		this.leftlegcloth.setTextureSize(64, 32);
		this.leftlegcloth.mirror = true;
		this.setRotation(leftlegcloth, 0F, 0F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.hair1.render(par7);
		this.hair2.render(par7);
		this.rightear.render(par7);
		this.leftear.render(par7);
		this.bodytop.render(par7);
		this.bodymiddle.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.tie.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.rightarm.render(par7);
		this.leftarm.render(par7);
		this.rightarmupper.render(par7);
		this.leftarmupper.render(par7);
		this.tail1.render(par7);
		this.tail2.render(par7);
		this.rightleg.render(par7);
		this.leftleg.render(par7);
		this.rightlegcloth.render(par7);
		this.leftlegcloth.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.hair1.rotateAngleY = this.head.rotateAngleY;
		this.hair2.rotateAngleY = this.head.rotateAngleY;
		this.rightear.rotateAngleY = this.head.rotateAngleY;
		this.rightear.rotateAngleX = this.head.rotateAngleX;
		this.leftear.rotateAngleY = this.head.rotateAngleY;
		this.leftear.rotateAngleX = this.head.rotateAngleX;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + 3.1415927F) * 0.4F * par2 * 0.5F;
		this.rightarmupper.rotateAngleX = this.rightarm.rotateAngleX;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.4F * par2 * 0.5F;
		this.leftarmupper.rotateAngleX = this.leftarm.rotateAngleX;
		this.rightchest.rotateAngleX = (MathHelper.cos(par1 * 0.6662F) * 0.8F * par2) + 0.7853982F;
		this.leftchest.rotateAngleX = this.rightchest.rotateAngleX;
		this.tail1.rotateAngleY = MathHelper.cos(par1 * 0.6662F) * 0.5F * par2;
		this.tail2.rotateAngleY = this.tail1.rotateAngleY;
		this.rightleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.1F * par2;
		this.rightlegcloth.rotateAngleX = this.rightleg.rotateAngleX;
		this.leftleg.rotateAngleX = MathHelper.cos(par1 * 0.6662F + 3.1415927F) * 0.1F * par2;
		this.leftlegcloth.rotateAngleX = this.leftleg.rotateAngleX;

        float f6;
        float f7;

        if (this.onGround > -9990.0F)
        {
            f6 = this.onGround;
            f6 = 1.0F - this.onGround;
            f6 *= f6;
            f6 *= f6;
            f6 = 1.0F - f6;
            f7 = MathHelper.sin(f6 * (float)Math.PI);
            float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
            
            this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)f7 * 1.2D + (double)f8));
            this.rightarmupper.rotateAngleX = this.rightarmupper.rotateAngleX;
            this.rightarm.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.rightarmupper.rotateAngleY = this.rightarmupper.rotateAngleY;
            this.rightarm.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F) + 0.1745329F;
            this.rightarmupper.rotateAngleZ = this.rightarmupper.rotateAngleZ;
        }
	}
}
