package gaia.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelGaiaValkyrie extends ModelBase{
	ModelRenderer head;
	ModelRenderer headaccessory;
	ModelRenderer hair1;
	ModelRenderer hair2;
	ModelRenderer rightfeather;
	ModelRenderer leftfeather;
	ModelRenderer headhelmet;
	ModelRenderer cape1;
	ModelRenderer cape2;
	ModelRenderer cape3;
	ModelRenderer bodytop;
	ModelRenderer bodymiddle;
	ModelRenderer bodymiddlebutton;
	ModelRenderer bodybottom;
	ModelRenderer rightchest;
	ModelRenderer leftchest;
	ModelRenderer rightwing;
	ModelRenderer leftwing;
	ModelRenderer rightpauldron;
	public static ModelRenderer rightarm;
	ModelRenderer rightgauntlet;
	ModelRenderer leftpauldron;
	ModelRenderer leftarm;
	ModelRenderer skirtmantle;
	ModelRenderer skirt1;
	ModelRenderer skirt2;
	ModelRenderer skirt3;
	ModelRenderer rightleg;
	ModelRenderer leftleg;

	public ModelGaiaValkyrie() {
		this.textureWidth = 128;
		this.textureHeight = 64;

		this.head = new ModelRenderer(this, 0, 0);
		this.head.addBox(-3F, -6F, -3F, 6, 6, 6);
		this.head.setRotationPoint(0F, -5F, 0F);
		this.head.setTextureSize(64, 32);
		this.head.mirror = true;
		this.setRotation(head, 0F, 0F, 0F);
		this.headaccessory = new ModelRenderer(this, 36, 0);
		this.headaccessory.addBox(-3.5F, -6.5F, -3.5F, 7, 7, 7);
		this.headaccessory.setRotationPoint(0F, -5F, 0F);
		this.headaccessory.setTextureSize(64, 32);
		this.headaccessory.mirror = true;
		this.setRotation(headaccessory, 0F, 0F, 0F);
		this.hair1 = new ModelRenderer(this, 36, 14);
		this.hair1.addBox(-4F, -6F, 3F, 8, 8, 3);
		this.hair1.setRotationPoint(0F, -5F, 0F);
		this.hair1.setTextureSize(64, 32);
		this.hair1.mirror = true;
		this.setRotation(hair1, 0.3490659F, 0F, 0F);
		this.hair2 = new ModelRenderer(this, 36, 25);
		this.hair2.addBox(-4.5F, -1F, 3.5F, 9, 9, 3);
		this.hair2.setRotationPoint(0F, -5F, 0F);
		this.hair2.setTextureSize(64, 32);
		this.hair2.mirror = true;
		this.setRotation(hair2, 0.2617994F, 0F, 0F);
		this.rightfeather = new ModelRenderer(this, 36, 37);
		this.rightfeather.addBox(-4.5F, -7F, 0F, 1, 6, 8);
		this.rightfeather.setRotationPoint(0F, -5F, 0F);
		this.rightfeather.setTextureSize(64, 32);
		this.rightfeather.mirror = true;
		this.setRotation(rightfeather, 0.3490659F, -0.2617994F, 0F);
		this.leftfeather = new ModelRenderer(this, 36, 37);
		this.leftfeather.addBox(3.5F, -7F, 0F, 1, 6, 8);
		this.leftfeather.setRotationPoint(0F, -5F, 0F);
		this.leftfeather.setTextureSize(64, 32);
		this.leftfeather.mirror = true;
		this.setRotation(leftfeather, 0.3490659F, 0.2617994F, 0F);
		this.headhelmet = new ModelRenderer(this, 36, 51);
		this.headhelmet.addBox(-3F, -7F, -4F, 6, 3, 4);
		this.headhelmet.setRotationPoint(0F, -5F, 0F);
		this.headhelmet.setTextureSize(64, 32);
		this.headhelmet.mirror = true;
		this.setRotation(headhelmet, 0F, 0F, 0F);
		this.cape1 = new ModelRenderer(this, 64, 0);
		this.cape1.addBox(-3.5F, 0F, 0.5F, 7, 4, 2);
		this.cape1.setRotationPoint(0F, -5F, 0F);
		this.cape1.setTextureSize(64, 32);
		this.cape1.mirror = true;
		this.setRotation(cape1, 0.3490659F, 0F, 0F);
		this.cape2 = new ModelRenderer(this, 64, 6);
		this.cape2.addBox(-4F, 3.5F, 0.5F, 8, 5, 3);
		this.cape2.setRotationPoint(0F, -5F, 0F);
		this.cape2.setTextureSize(64, 32);
		this.cape2.mirror = true;
		this.setRotation(cape2, 0.2617994F, 0F, 0F);
		this.cape3 = new ModelRenderer(this, 64, 14);
		this.cape3.addBox(-4.5F, 8F, 1.5F, 9, 6, 3);
		this.cape3.setRotationPoint(0F, -5F, 0F);
		this.cape3.setTextureSize(64, 32);
		this.cape3.mirror = true;
		this.setRotation(cape3, 0.1745329F, 0F, 0F);
		this.bodytop = new ModelRenderer(this, 0, 12);
		this.bodytop.addBox(-2.5F, 0F, -1.5F, 5, 5, 3);
		this.bodytop.setRotationPoint(0F, -5F, 0F);
		this.bodytop.setTextureSize(64, 32);
		this.bodytop.mirror = true;
		this.setRotation(bodytop, -0.0872665F, 0F, 0F);
		this.bodymiddle = new ModelRenderer(this, 0, 20);
		this.bodymiddle.addBox(-2F, 4.5F, -1.5F, 4, 3, 2);
		this.bodymiddle.setRotationPoint(0F, -5F, 0F);
		this.bodymiddle.setTextureSize(64, 32);
		this.bodymiddle.mirror = true;
		this.setRotation(bodymiddle, 0F, 0F, 0F);
		this.bodymiddlebutton = new ModelRenderer(this, 0, 20);
		this.bodymiddlebutton.addBox(-0.5F, 5F, -1.6F, 1, 2, 0);
		this.bodymiddlebutton.setRotationPoint(0F, -5F, 0F);
		this.bodymiddlebutton.setTextureSize(64, 32);
		this.bodymiddlebutton.mirror = true;
		this.setRotation(bodymiddlebutton, 0F, 0F, 0F);
		this.bodybottom = new ModelRenderer(this, 0, 25);
		this.bodybottom.addBox(-2.5F, 7F, -2.5F, 5, 3, 3);
		this.bodybottom.setRotationPoint(0F, -5F, 0F);
		this.bodybottom.setTextureSize(64, 32);
		this.bodybottom.mirror = true;
		this.setRotation(bodybottom, 0.0872665F, 0F, 0F);
		this.rightchest = new ModelRenderer(this, 0, 31);
		this.rightchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.rightchest.setRotationPoint(-1.3F, -3F, -1.5F);
		this.rightchest.setTextureSize(64, 32);
		this.rightchest.mirror = true;
		this.setRotation(rightchest, 0.7853982F, 0.1745329F, 0.0872665F);
		this.leftchest = new ModelRenderer(this, 8, 31);
		this.leftchest.addBox(-1F, -1F, -1F, 2, 2, 2);
		this.leftchest.setRotationPoint(1.3F, -3F, -1.5F);
		this.leftchest.setTextureSize(64, 32);
		this.leftchest.mirror = true;
		this.setRotation(leftchest, 0.7853982F, -0.1745329F, -0.0872665F);
		this.rightwing = new ModelRenderer(this, 74, 34);
		this.rightwing.addBox(0F, 0F, 0.5F, 0, 12, 18);
		this.rightwing.setRotationPoint(-2F, -4F, 1F);
		this.rightwing.setTextureSize(64, 32);
		this.rightwing.mirror = true;
		this.setRotation(rightwing, 0.5235988F, -0.9599311F, 0F);
		this.leftwing = new ModelRenderer(this, 92, 34);
		this.leftwing.addBox(-1F, 0F, 0.5F, 0, 12, 18);
		this.leftwing.setRotationPoint(2F, -4F, 1F);
		this.leftwing.setTextureSize(64, 32);
		this.leftwing.mirror = true;
		this.setRotation(leftwing, 0.5235988F, 0.9599311F, 0F);
		this.rightpauldron = new ModelRenderer(this, 64, 23);
		this.rightpauldron.addBox(-4F, -2F, -2F, 4, 3, 4);
		this.rightpauldron.setRotationPoint(-2.5F, -3F, 0F);
		this.rightpauldron.setTextureSize(64, 32);
		this.rightpauldron.mirror = true;
		this.setRotation(rightpauldron, 0.0872665F, 0F, -0.1745329F);
		this.rightarm = new ModelRenderer(this, 16, 12);
		this.rightarm.addBox(-2F, -1F, -1F, 2, 10, 2);
		this.rightarm.setRotationPoint(-2.5F, -3F, 0F);
		this.rightarm.setTextureSize(64, 32);
		this.rightarm.mirror = true;
		this.setRotation(rightarm, 0.0872665F, 0F, 0.1745329F);
		this.rightgauntlet = new ModelRenderer(this, 64, 30);
		this.rightgauntlet.addBox(-2.5F, 3.5F, -1.5F, 2, 6, 3);
		this.rightgauntlet.setRotationPoint(-2.5F, -3F, 0F);
		this.rightgauntlet.setTextureSize(64, 32);
		this.rightgauntlet.mirror = true;
		this.setRotation(rightgauntlet, 0.0872665F, 0F, 0.1745329F);
		this.leftpauldron = new ModelRenderer(this, 80, 23);
		this.leftpauldron.addBox(0F, -2F, -2F, 4, 3, 4);
		this.leftpauldron.setRotationPoint(2.5F, -3F, 0F);
		this.leftpauldron.setTextureSize(64, 32);
		this.leftpauldron.mirror = true;
		this.setRotation(leftpauldron, 0.0872665F, 0F, 0.1745329F);
		this.leftarm = new ModelRenderer(this, 16, 12);
		this.leftarm.addBox(0F, -1F, -1F, 2, 10, 2);
		this.leftarm.setRotationPoint(2.5F, -3F, 0F);
		this.leftarm.setTextureSize(64, 32);
		this.leftarm.mirror = true;
		this.setRotation(leftarm, 0.0872665F, 0F, -0.1745329F);
		this.skirtmantle = new ModelRenderer(this, 96, 0);
		this.skirtmantle.addBox(-3F, -1F, -2F, 6, 4, 4);
		this.skirtmantle.setRotationPoint(0F, 5F, 0F);
		this.skirtmantle.setTextureSize(64, 32);
		this.skirtmantle.mirror = true;
		this.setRotation(skirtmantle, 0.0872665F, 0F, 0F);
		this.skirt1 = new ModelRenderer(this, 96, 8);
		this.skirt1.addBox(-3.5F, 1F, -1.5F, 7, 4, 4);
		this.skirt1.setRotationPoint(0F, 5F, 0F);
		this.skirt1.setTextureSize(64, 32);
		this.skirt1.mirror = true;
		this.setRotation(skirt1, 0.1745329F, 0F, 0F);
		this.skirt2 = new ModelRenderer(this, 96, 16);
		this.skirt2.addBox(-4F, 3F, -1.5F, 8, 5, 4);
		this.skirt2.setRotationPoint(0F, 5F, 0F);
		this.skirt2.setTextureSize(64, 32);
		this.skirt2.mirror = true;
		this.setRotation(skirt2, 0.2617994F, 0F, 0F);
		this.skirt3 = new ModelRenderer(this, 96, 25);
		this.skirt3.addBox(-5F, 6F, -1.5F, 10, 5, 4);
		this.skirt3.setRotationPoint(0F, 5F, 0F);
		this.skirt3.setTextureSize(64, 32);
		this.skirt3.mirror = true;
		this.setRotation(skirt3, 0.3490659F, 0F, 0F);
		this.rightleg = new ModelRenderer(this, 24, 12);
		this.rightleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.rightleg.setRotationPoint(-1.5F, 5F, 0F);
		this.rightleg.setTextureSize(64, 32);
		this.rightleg.mirror = true;
		this.setRotation(rightleg, 0.1745329F, 0.0872665F, 0F);
		this.leftleg = new ModelRenderer(this, 24, 12);
		this.leftleg.addBox(-1F, 0F, -1F, 2, 13, 2);
		this.leftleg.setRotationPoint(1.5F, 5F, 0F);
		this.leftleg.setTextureSize(64, 32);
		this.leftleg.mirror = true;
		this.setRotation(leftleg, 0.1745329F, -0.0872665F, 0F);
	}

	public void render(Entity entity, float par2, float par3, float par4, float par5, float par6, float par7) {
		super.render(entity, par2, par3, par4, par5, par6, par7);
		this.setRotationAngles(par2, par3, par4, par5, par6, par7);
		this.head.render(par7);
		this.headaccessory.render(par7);
		this.hair1.render(par7);
		this.hair2.render(par7);
		this.rightfeather.render(par7);
		this.leftfeather.render(par7);
		this.headhelmet.render(par7);
		this.cape1.render(par7);
		this.cape2.render(par7);
		this.cape3.render(par7);
		this.bodytop.render(par7);
		this.bodymiddle.render(par7);
		this.bodymiddlebutton.render(par7);
		this.bodybottom.render(par7);
		this.rightchest.render(par7);
		this.leftchest.render(par7);
		this.rightwing.render(par7);
		this.leftwing.render(par7);
		this.rightpauldron.render(par7);
		this.rightarm.render(par7);
		this.rightgauntlet.render(par7);
		this.leftpauldron.render(par7);
		this.leftarm.render(par7);
		this.skirtmantle.render(par7);
		this.skirt1.render(par7);
		this.skirt2.render(par7);
		this.skirt3.render(par7);
		this.rightleg.render(par7);
		this.leftleg.render(par7);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6) {
		this.head.rotateAngleY = par4 / 57.295776F;
		this.head.rotateAngleX = par5 / 57.295776F;
		this.headaccessory.rotateAngleY = this.head.rotateAngleY;
		this.headaccessory.rotateAngleX = this.head.rotateAngleX;
		this.hair1.rotateAngleY = this.head.rotateAngleY;
		this.hair2.rotateAngleY = this.head.rotateAngleY;
		this.rightfeather.rotateAngleY = this.head.rotateAngleY;
		this.rightfeather.rotateAngleX = this.head.rotateAngleX + 0.3490659F;
		this.leftfeather.rotateAngleY = this.head.rotateAngleY;
		this.leftfeather.rotateAngleX = this.head.rotateAngleX + 0.3490659F;
		this.headhelmet.rotateAngleY = this.head.rotateAngleY;
		this.headhelmet.rotateAngleX = this.head.rotateAngleX;
		this.rightarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F + (float)Math.PI) * 0.8F * par2 * 0.5F;
		this.leftarm.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 0.8F * par2 * 0.5F;
		this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX + 0.0872665F;
		this.leftpauldron.rotateAngleX = this.leftarm.rotateAngleX + 0.0872665F;
		this.rightgauntlet.rotateAngleX = this.rightarm.rotateAngleX + 0.0872665F;
		this.rightarm.rotateAngleX += 0.0872665F;
		this.leftarm.rotateAngleX += 0.0872665F;
		this.rightwing.rotateAngleY = MathHelper.cos(par3 * 0.4F + (float)Math.PI) * 1.0F * 0.5F;
		this.leftwing.rotateAngleY = MathHelper.cos(par3 * 0.4F) * 1.0F * 0.5F;
		this.rightwing.rotateAngleZ = 0.0F;
		this.leftwing.rotateAngleZ = 0.0F;
		this.rightwing.rotateAngleY -= 0.9599311F;
		this.leftwing.rotateAngleY += 0.9599311F;
		
        float f6;
        float f7;

        if (this.onGround > -9990.0F)
        {
            f6 = this.onGround;
            f6 = 1.0F - this.onGround;
            f6 *= f6;
            f6 *= f6;
            f6 = 1.0F - f6;
            f7 = MathHelper.sin(f6 * (float)Math.PI);
            float f8 = MathHelper.sin(this.onGround * (float)Math.PI) * -(this.head.rotateAngleX - 0.7F) * 0.75F;
            
            this.rightarm.rotateAngleX = (float)((double)this.rightarm.rotateAngleX - ((double)f7 * 1.2D + (double)f8)) + 0.0872665F;
            this.rightpauldron.rotateAngleX = this.rightarm.rotateAngleX;
            this.rightgauntlet.rotateAngleX = this.rightarm.rotateAngleX;
            this.rightarm.rotateAngleY += (this.bodytop.rotateAngleY * 2.0F);
            this.rightpauldron.rotateAngleY = this.rightarm.rotateAngleY;
            this.rightgauntlet.rotateAngleY = this.rightarm.rotateAngleY;
            this.rightarm.rotateAngleZ = (MathHelper.sin(this.onGround * (float)Math.PI) * -0.4F);
            this.rightpauldron.rotateAngleZ = this.rightarm.rotateAngleZ - 0.1745329F;
            this.rightgauntlet.rotateAngleZ = this.rightarm.rotateAngleZ + 0.1745329F;
            this.rightarm.rotateAngleZ = this.rightarm.rotateAngleZ + 0.1745329F;
        }
	}
}
