package gaia.datagen.server;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import gaia.registry.GaiaLootTables;
import gaia.registry.GaiaRegistry;
import gaia.registry.GaiaTags;
import net.minecraft.advancements.critereon.EntityEquipmentPredicate;
import net.minecraft.advancements.critereon.EntityPredicate;
import net.minecraft.advancements.critereon.ItemPredicate;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.loot.BlockLoot;
import net.minecraft.data.loot.EntityLoot;
import net.minecraft.data.loot.LootTableProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.tags.ItemTags;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootContext;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.LootTable.Builder;
import net.minecraft.world.level.storage.loot.LootTables;
import net.minecraft.world.level.storage.loot.ValidationContext;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.entries.LootTableReference;
import net.minecraft.world.level.storage.loot.entries.TagEntry;
import net.minecraft.world.level.storage.loot.functions.LootingEnchantFunction;
import net.minecraft.world.level.storage.loot.functions.SetEnchantmentsFunction;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.functions.SmeltItemFunction;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSet;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.minecraft.world.level.storage.loot.predicates.LootItemEntityPropertyCondition;
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceWithLootingCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;
import net.minecraftforge.common.Tags;
import net.minecraftforge.registries.RegistryObject;

import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.stream.Stream;

public class GaiaLoot extends LootTableProvider {
	public GaiaLoot(DataGenerator gen) {
		super(gen);
	}

	@Override
	protected List<Pair<Supplier<Consumer<BiConsumer<ResourceLocation, Builder>>>, LootContextParamSet>> getTables() {
		return ImmutableList.of(
				Pair.of(GaiaBlockTables::new, LootContextParamSets.BLOCK),
				Pair.of(GaiaEntityLoot::new, LootContextParamSets.ENTITY));
	}

	public static class GaiaBlockTables extends BlockLoot {
		@Override
		protected void addTables() {
			this.dropSelf(GaiaRegistry.BUST_GORGON.get());
			this.dropSelf(GaiaRegistry.BUST_SPHINX.get());
			this.dropSelf(GaiaRegistry.BUST_VALKYRIE.get());
			this.dropSelf(GaiaRegistry.BUST_VAMPIRE.get());
			this.dropSelf(GaiaRegistry.BUST_MINOTAUR.get());
			this.dropSelf(GaiaRegistry.DOLL_CREEPER_GIRL.get());
			this.dropSelf(GaiaRegistry.DOLL_ENDER_GIRL.get());
			this.dropSelf(GaiaRegistry.DOLL_SLIME_GIRL.get());
			this.dropSelf(GaiaRegistry.DOLL_MAID.get());
			this.dropSelf(GaiaRegistry.DOLL_DULLAHAN.get());
			this.dropSelf(GaiaRegistry.DOLL_MERMAID.get());
			this.dropSelf(GaiaRegistry.DOLL_NINE_TAILS.get());
			this.dropSelf(GaiaRegistry.DOLL_DRYAD.get());
			this.dropSelf(GaiaRegistry.DECO_GARDEN_GNOME.get());
			this.dropSelf(GaiaRegistry.DECO_MANDRAGORA_POT.get());
			this.dropSelf(GaiaRegistry.DECO_NEST_HARPY.get());
			this.dropSelf(GaiaRegistry.PEARL_BLOCK.get());
		}

		@Override
		protected Iterable<Block> getKnownBlocks() {
			return (Iterable<Block>) GaiaRegistry.BLOCKS.getEntries().stream().map(RegistryObject::get)::iterator;
		}
	}

	private static class GaiaEntityLoot extends EntityLoot {

		@Override
		protected void addTables() {
			this.add(GaiaRegistry.ANT_HILL.getEntityType(), LootTable.lootTable());
			this.add(GaiaRegistry.ANT_WORKER.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.GREEN_DYE)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.HONEYDEW.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.ANT_SALVAGER.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BOOK)
									.apply(new SetEnchantmentsFunction.Builder().withEnchantment(Enchantments.MOB_LOOTING, ConstantValue.exactly(1.0F)))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.ANUBIS.getEntityType(), LootTable.lootTable()
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
											.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
									.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
									.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.add(LootItem.lootTableItem(GaiaRegistry.BOOK_OF_MEMORY.get())
											.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
//					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
//							.add(LootItem.lootTableItem(GaiaRegistry.SPAWN_WERESHEEP.get())
//							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.ARACHNE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.STONE_COAL.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOOK_OF_MEMORY.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.BANSHEE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SOULFIRE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_NIGHTMARE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.BEE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BONE_MEAL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.HONEYDEW.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.BEHENDER.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ENDER_PEARL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_END.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_ENDER.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.BONE_KNIGHT.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.REDSTONE)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get()))
							.add(TagEntry.expandTag(Tags.Items.STORAGE_BLOCKS_REDSTONE))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.SKELETON_SKULL)
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.CECAELIA.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SHINY_PEARL.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.CLAY)
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.25F, 0.01F))
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BOOK)
									.apply(new SetEnchantmentsFunction.Builder().withEnchantment(Enchantments.FISHING_LUCK, ConstantValue.exactly(1.0F)))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.CENTAUR.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.LEATHER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.CHEST.getEntityType(), LootTable.lootTable());
			this.add(GaiaLootTables.CHEST_TABLES, LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootTableReference.lootTableReference(BuiltInLootTables.SIMPLE_DUNGEON))
					)
			);
			this.add(GaiaRegistry.COBBLE_GOLEM.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.CHEST_JUNGLE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.TOTEM_FRAGMENT.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_METAL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.CREEP.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.GUNPOWDER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_CREEPER_GIRL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.CYAN_FLOWER.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.DANDELION)
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.1F, 0.01F)))
							.add(LootItem.lootTableItem(Items.POPPY)))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MANDRAKE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.0625F, 0.01F))
									.when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.KILLER,
											EntityPredicate.Builder.entity()
													.equipment(EntityEquipmentPredicate.Builder.equipment()
															.mainhand(ItemPredicate.Builder.item().of(GaiaTags.TOOLS_SHOVELS).build()).build()))
									)
							)
					)
			);
			this.add(GaiaRegistry.CYCLOPS.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FUR.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BOOK)
									.apply(new SetEnchantmentsFunction.Builder().withEnchantment(Enchantments.SHARPNESS, ConstantValue.exactly(1.0F)))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.KNUCKLES.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.DEATHWORD.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.PAPER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BOOK)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.DRYAD.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.TAPROOT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(ItemTags.LOGS_THAT_BURN)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F))))
							.when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.KILLER,
									EntityPredicate.Builder.entity().equipment(EntityEquipmentPredicate.Builder.equipment()
											.mainhand(ItemPredicate.Builder.item().of(GaiaTags.TOOLS_AXES).build()).build()))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_DRYAD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.DULLAHAN.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SOULFIRE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_DULLAHAN.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.DWARF.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
			);
			this.add(GaiaLootTables.DWARF_RANGED, LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ARROW)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaLootTables.DWARF_MINER, LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.1F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
			);
			this.add(GaiaRegistry.ENDER_EYE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ENDER_PEARL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_ENDER_GIRL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ENDER_PEARL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_END.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_ENDER_GIRL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.ELYTRA_FRAGMENT.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.FLESH_LICH.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.GEMS_LAPIS)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get()))
							.add(TagEntry.expandTag(Tags.Items.STORAGE_BLOCKS_LAPIS))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ZOMBIE_HEAD)
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.SLIME_BALL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_SLIME_GIRL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.GOBLIN.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.GOBLIN_FERAL.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
			);
			this.add(GaiaRegistry.GRYPHON.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.FEATHER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.HARPY.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.FEATHER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DECO_NEST_HARPY.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.HUNTER.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.ROTTEN_HEART.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.KOBOLD.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FUR.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.MANDRAGORA.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.TAPROOT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MANDRAKE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F))))
							.when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.KILLER,
									EntityPredicate.Builder.entity().equipment(EntityEquipmentPredicate.Builder.equipment()
											.mainhand(ItemPredicate.Builder.item().of(GaiaTags.TOOLS_SHOVELS).build()).build()))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F)))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DECO_GARDEN_GNOME.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.MATANGO.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.MUSHROOMS)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))

			);
			this.add(GaiaRegistry.MERMAID.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SHINY_PEARL.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.PRISMARINE_SHARD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OLD.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_MERMAID.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.SEASHELL_HAIRPIN.get())))
			);
			this.add(GaiaRegistry.MINOTAUR.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.GOLDEN_APPLE_PIE_SLICE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_DIAMOND)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_EMERALD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_DIAMOND.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BUST_MINOTAUR_ITEM.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.HEAVY_BARBELL.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.RING_OF_HASTE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.MINOTAURUS.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.LEATHER)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F)).when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_BATTLE.get())))
			);
			this.add(GaiaLootTables.MINOTAURUS_RANGED, LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.ARROW)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F)).when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())))
			);
			this.add(GaiaRegistry.MIMIC.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootTableReference.lootTableReference(EntityType.CREEPER.getDefaultLootTable()))
							.add(LootTableReference.lootTableReference(EntityType.SPIDER.getDefaultLootTable()))
							.add(LootTableReference.lootTableReference(EntityType.ENDERMAN.getDefaultLootTable()))
							.add(LootTableReference.lootTableReference(EntityType.SLIME.getDefaultLootTable()))
							.add(LootTableReference.lootTableReference(EntityType.ZOMBIE.getDefaultLootTable()))
							.add(LootTableReference.lootTableReference(EntityType.SKELETON.getDefaultLootTable())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.PREMIUM_MONSTER_FEED.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_RECORD.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_HUNGER.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.GRAVEMITE.getEntityType(), LootTable.lootTable());
			this.add(GaiaRegistry.MUMMY.getEntityType(), LootTable.lootTable() //TODO: Mummy drops (Bones / Rotten Flesh (50/50))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BONE))
							.add(LootItem.lootTableItem(Items.ROTTEN_FLESH))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.NAGA.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootTableReference.lootTableReference(BuiltInLootTables.FISHING_FISH)
									.apply(SmeltItemFunction.smelted().when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
			);
			this.add(GaiaRegistry.NINE_TAILS.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SOULFIRE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FAN_FIRE.get())
									.apply(new SetEnchantmentsFunction.Builder()
											.withEnchantment(Enchantments.FIRE_ASPECT, ConstantValue.exactly(2.0F))
											.withEnchantment(Enchantments.KNOCKBACK, ConstantValue.exactly(1.0F)))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DOLL_NINE_TAILS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.ONI.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SOULFIRE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.BOOK)
									.apply(new SetEnchantmentsFunction.Builder().withEnchantment(Enchantments.SHARPNESS, ConstantValue.exactly(1.0F)))
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.ORC.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
			);
			this.add(GaiaRegistry.SATYRESS.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.SHAMAN.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.ROTTEN_HEART.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get())))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOOK_OF_MEMORY.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.SHARKO.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SHINY_PEARL.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.PRISMARINE_SHARD)
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.25F, 0.01F))
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_OVERWORLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_BUFF.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.SIREN.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootTableReference.lootTableReference(BuiltInLootTables.FISHING_FISH)
									.apply(SmeltItemFunction.smelted().when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.THIS, ENTITY_ON_FIRE)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_ARROWS.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.SLUDGE_GIRL.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.SLIME_BALL)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.SPHINX.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.GOLDEN_APPLE_PIE_SLICE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_DIAMOND)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_EMERALD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_DIAMOND.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BUST_SPHINX.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.RING_OF_JUMP.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.CHEST_DESERT.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.SPORELING.getEntityType(), LootTable.lootTable());
			this.add(GaiaRegistry.SPRIGGAN.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.TAPROOT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.OAK_LOG)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F))))
							.when(LootItemEntityPropertyCondition.hasProperties(LootContext.EntityTarget.KILLER,
									EntityPredicate.Builder.entity().equipment(EntityEquipmentPredicate.Builder.equipment().mainhand(ItemPredicate.Builder.item().of(GaiaTags.TOOLS_AXES).build()).build()))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WEAPON_BOOK_NATURE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.SUCCUBUS.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FIRESHARD.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.QUARTZ))
							.add(LootItem.lootTableItem(Items.GLOWSTONE_DUST)))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_NETHER.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.TOAD.getEntityType(), LootTable.lootTable()
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.add(LootItem.lootTableItem(Items.SLIME_BALL)
											.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
											.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
											.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
							.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
									.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
											.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
//					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F)) //Poison Trinket Accessory
//							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
//									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.VALKYRIE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.GOLDEN_APPLE_PIE_SLICE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_DIAMOND)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(GaiaTags.NUGGETS_EMERALD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_DIAMOND.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BUST_VALKYRIE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.RING_OF_SPEED.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.WERECAT.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.MEAT.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.WITCH.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.NETHER_WART_JAM.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOOK_OF_MEMORY.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.DECO_MANDRAGORA_POT.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.WITHER_COW.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.WITHERED_BRAIN.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(Items.QUARTZ))
							.add(LootItem.lootTableItem(Items.GLOWSTONE_DUST)))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_NETHER.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
			);
			this.add(GaiaRegistry.WIZARD_HARPY.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.SOULFIRE.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_IRON)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_IRON.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOOK_OF_MEMORY.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);
			this.add(GaiaRegistry.YUKI_ONNA.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FUR.get())
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
									.apply(LootingEnchantFunction.lootingMultiplier(UniformGenerator.between(0.0F, 1.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(TagEntry.expandTag(Tags.Items.NUGGETS_GOLD)
									.apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 3.0F)))))
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.025F, 0.01F))
							.add(LootItem.lootTableItem(GaiaRegistry.BOX_GOLD.get()))
							.add(LootItem.lootTableItem(GaiaRegistry.BAG_BOOK.get()))
					)
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootItem.lootTableItem(GaiaRegistry.FAN_ICE.get())
									.when(LootItemRandomChanceWithLootingCondition.randomChanceAndLootingBoost(0.01F, 0.01F))))
			);

			this.add(GaiaRegistry.HORSE.getEntityType(), LootTable.lootTable()
					.withPool(LootPool.lootPool().setRolls(ConstantValue.exactly(1.0F))
							.add(LootTableReference.lootTableReference(EntityType.ZOMBIE_HORSE.getDefaultLootTable())))
			);
		}

		@Override
		protected Iterable<EntityType<?>> getKnownEntities() {
			Stream<EntityType<?>> entities = GaiaRegistry.ENTITIES.getEntries().stream().map(RegistryObject::get);
			return (Iterable<EntityType<?>>) entities::iterator;
		}
	}

	@Override
	protected void validate(Map<ResourceLocation, LootTable> map, ValidationContext validationContext) {
		//A list of loot tables that don't get validated because they most likely reference other loot tables which would cause it to fail
		List<ResourceLocation> ignored = List.of(
				GaiaLootTables.CHEST_TABLES,
				GaiaRegistry.CHEST.getEntityType().getDefaultLootTable(),
				GaiaRegistry.HORSE.getEntityType().getDefaultLootTable(),
				GaiaRegistry.MIMIC.getEntityType().getDefaultLootTable(),
				GaiaRegistry.NAGA.getEntityType().getDefaultLootTable(),
				GaiaRegistry.SIREN.getEntityType().getDefaultLootTable()
		);
		map.forEach((name, table) -> {
			if (!ignored.contains(name)) {
				LootTables.validate(validationContext, name, table);
			}
		});
	}
}
