package gaia.registry;

import gaia.entity.AntSalvager;
import gaia.entity.AntWorker;
import gaia.entity.Anubis;
import gaia.entity.Arachne;
import gaia.entity.Banshee;
import gaia.entity.Bee;
import gaia.entity.Behender;
import gaia.entity.BoneKnight;
import gaia.entity.Cecaelia;
import gaia.entity.Centaur;
import gaia.entity.CobbleGolem;
import gaia.entity.CobblestoneGolem;
import gaia.entity.Creep;
import gaia.entity.Cyclops;
import gaia.entity.Deathword;
import gaia.entity.Dryad;
import gaia.entity.Dullahan;
import gaia.entity.Dwarf;
import gaia.entity.EnderDragonGirl;
import gaia.entity.EnderEye;
import gaia.entity.FleshLich;
import gaia.entity.GaiaHorse;
import gaia.entity.GelatinousSlime;
import gaia.entity.Goblin;
import gaia.entity.GoblinFeral;
import gaia.entity.GraveMite;
import gaia.entity.Gryphon;
import gaia.entity.Harpy;
import gaia.entity.Hunter;
import gaia.entity.Kobold;
import gaia.entity.Mandragora;
import gaia.entity.Matango;
import gaia.entity.Mermaid;
import gaia.entity.Mimic;
import gaia.entity.Minotaur;
import gaia.entity.Minotaurus;
import gaia.entity.Mummy;
import gaia.entity.Naga;
import gaia.entity.NineTails;
import gaia.entity.Oni;
import gaia.entity.Orc;
import gaia.entity.Satyress;
import gaia.entity.Shaman;
import gaia.entity.Sharko;
import gaia.entity.Siren;
import gaia.entity.SludgeGirl;
import gaia.entity.Sphinx;
import gaia.entity.Sporeling;
import gaia.entity.Spriggan;
import gaia.entity.Succubus;
import gaia.entity.Toad;
import gaia.entity.Valkyrie;
import gaia.entity.Werecat;
import gaia.entity.Witch;
import gaia.entity.WitherCow;
import gaia.entity.WizardHarpy;
import gaia.entity.YukiOnna;
import gaia.entity.prop.AntHill;
import gaia.entity.prop.Chest;
import gaia.entity.prop.CyanFlower;
import gaia.entity.trader.CreeperGirl;
import gaia.entity.trader.EnderGirl;
import gaia.entity.trader.SlimeGirl;
import gaia.entity.trader.Trader;
import net.minecraft.world.entity.SpawnPlacementTypes;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.level.levelgen.Heightmap;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.entity.EntityAttributeCreationEvent;
import net.neoforged.neoforge.event.entity.RegisterSpawnPlacementsEvent;

@EventBusSubscriber
public class GaiaSpawning {

	@SubscribeEvent
	public static void entityAttributes(RegisterSpawnPlacementsEvent event) {
		event.register(GaiaRegistry.ANT_HILL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntHill::checkAntHillSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ANT_WORKER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntWorker::checkAntWorkerSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ANT_SALVAGER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, AntSalvager::checkAntSalvagerSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ARACHNE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Arachne::checkArachneSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ANUBIS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Anubis::checkAnubisSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.BANSHEE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Banshee::checkBansheeSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.BEE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Bee::checkBeeSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.BEHENDER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Behender::checkBehenderSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.BONE_KNIGHT.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, BoneKnight::checkBoneKnightSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CECAELIA.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cecaelia::checkCecaeliaSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CENTAUR.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Centaur::checkCentaurSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CHEST.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Chest::checkChestSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.COBBLE_GOLEM.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CobbleGolem::checkCobbleGolemSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CobblestoneGolem::checkCobblestoneGolemSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CREEP.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Creep::checkCreepSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CYCLOPS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Cyclops::checkCyclopsSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CYAN_FLOWER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CyanFlower::checkCyanFlowerSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.DEATHWORD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Deathword::checkDeathwordSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.DRYAD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dryad::checkDryadSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.DULLAHAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dullahan::checkDullahanSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.DWARF.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Dwarf::checkDwarfSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ENDER_EYE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderEye::checkEnderEyeSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderDragonGirl::checkEnderDragonGirlSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.FLESH_LICH.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, FleshLich::checkFleshLichSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GelatinousSlime::checkGelatinousSlimeSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.GOBLIN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Goblin::checkGoblinSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.GOBLIN_FERAL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GoblinFeral::checkGoblinFeralSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.GRAVEMITE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, GraveMite::checkMiteSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.GRYPHON.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Gryphon::checkGryphonSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.HARPY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Harpy::checkHarpySpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.HUNTER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Hunter::checkHunterSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.KOBOLD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Kobold::checkKoboldSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MANDRAGORA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mandragora::checkMandragoraSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MATANGO.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Matango::checkMatangoSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MERMAID.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mermaid::checkMermaidSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MINOTAUR.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Minotaur::checkMinotaurSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MINOTAURUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Minotaurus::checkMinotaurusSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MUMMY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mummy::checkMummySpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.MIMIC.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Mimic::checkMimicSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.NAGA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Naga::checkNagaSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.NINE_TAILS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, NineTails::checkNineTailsSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ONI.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Oni::checkOniSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ORC.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Orc::checkOrcSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SATYRESS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Satyress::checkSatyressSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SHAMAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Shaman::checkShamanSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SHARKO.getEntityType(), SpawnPlacementTypes.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sharko::checkSharkoSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SIREN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Siren::checkSirenSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SLUDGE_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SludgeGirl::checkSludgeGirlSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SPHINX.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sphinx::checkSphinxSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SPORELING.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Sporeling::checkSporelingSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SPRIGGAN.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Spriggan::checkSprigganSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SUCCUBUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Succubus::checkSuccubusSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.TOAD.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Toad::checkToadSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.VALKYRIE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Valkyrie::checkValkyrieSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.WERECAT.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Werecat::checkWerecatSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.WITCH.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Witch::checkWitchSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.WITHER_COW.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, WitherCow::checkWitherCowSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.WIZARD_HARPY.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, WizardHarpy::checkWizardHarpySpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.YUKI_ONNA.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, YukiOnna::checkYukiOnnaSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);

		event.register(GaiaRegistry.TRADER.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Trader::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.CREEPER_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, CreeperGirl::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.ENDER_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, EnderGirl::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
//		event.register(GaiaRegistry.HOLSTAURUS.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Holstaurus::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
		event.register(GaiaRegistry.SLIME_GIRL.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, SlimeGirl::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
//		event.register(GaiaRegistry.WERESHEEP.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Weresheep::checkMobSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);

		event.register(GaiaRegistry.HORSE.getEntityType(), SpawnPlacementTypes.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Animal::checkAnimalSpawnRules, RegisterSpawnPlacementsEvent.Operation.AND);
	}

	@SubscribeEvent
	public static void registerEntityAttributes(EntityAttributeCreationEvent event) {
		event.put(GaiaRegistry.ANT_HILL.getEntityType(), AntHill.createAttributes().build());
		event.put(GaiaRegistry.ANT_WORKER.getEntityType(), AntWorker.createAttributes().build());
		event.put(GaiaRegistry.ANT_SALVAGER.getEntityType(), AntSalvager.createAttributes().build());
		event.put(GaiaRegistry.ANUBIS.getEntityType(), Anubis.createAttributes().build());
		event.put(GaiaRegistry.ARACHNE.getEntityType(), Arachne.createAttributes().build());
		event.put(GaiaRegistry.BANSHEE.getEntityType(), Banshee.createAttributes().build());
		event.put(GaiaRegistry.BEE.getEntityType(), Bee.createAttributes().build());
		event.put(GaiaRegistry.BEHENDER.getEntityType(), Behender.createAttributes().build());
		event.put(GaiaRegistry.BONE_KNIGHT.getEntityType(), BoneKnight.createAttributes().build());
		event.put(GaiaRegistry.CENTAUR.getEntityType(), Centaur.createAttributes().build());
		event.put(GaiaRegistry.CHEST.getEntityType(), Chest.createAttributes().build());
		event.put(GaiaRegistry.COBBLE_GOLEM.getEntityType(), CobbleGolem.createAttributes().build());
		event.put(GaiaRegistry.COBBLESTONE_GOLEM.getEntityType(), CobblestoneGolem.createAttributes().build());
		event.put(GaiaRegistry.CREEP.getEntityType(), Creep.createAttributes().build());
		event.put(GaiaRegistry.CYCLOPS.getEntityType(), Cyclops.createAttributes().build());
		event.put(GaiaRegistry.CYAN_FLOWER.getEntityType(), CyanFlower.createAttributes().build());
		event.put(GaiaRegistry.CECAELIA.getEntityType(), Cecaelia.createAttributes().build());
		event.put(GaiaRegistry.DEATHWORD.getEntityType(), Deathword.createAttributes().build());
		event.put(GaiaRegistry.DRYAD.getEntityType(), Dryad.createAttributes().build());
		event.put(GaiaRegistry.DULLAHAN.getEntityType(), Dullahan.createAttributes().build());
		event.put(GaiaRegistry.DWARF.getEntityType(), Dwarf.createAttributes().build());
		event.put(GaiaRegistry.ENDER_EYE.getEntityType(), EnderEye.createAttributes().build());
		event.put(GaiaRegistry.ENDER_DRAGON_GIRL.getEntityType(), EnderDragonGirl.createAttributes().build());
		event.put(GaiaRegistry.FLESH_LICH.getEntityType(), FleshLich.createAttributes().build());
		event.put(GaiaRegistry.GELATINOUS_SLIME.getEntityType(), GelatinousSlime.createAttributes().build());
		event.put(GaiaRegistry.GOBLIN.getEntityType(), Goblin.createAttributes().build());
		event.put(GaiaRegistry.GOBLIN_FERAL.getEntityType(), GoblinFeral.createAttributes().build());
		event.put(GaiaRegistry.GRAVEMITE.getEntityType(), GraveMite.createAttributes().build());
		event.put(GaiaRegistry.GRYPHON.getEntityType(), Gryphon.createAttributes().build());
		event.put(GaiaRegistry.HARPY.getEntityType(), Harpy.createAttributes().build());
		event.put(GaiaRegistry.HUNTER.getEntityType(), Hunter.createAttributes().build());
		event.put(GaiaRegistry.KOBOLD.getEntityType(), Kobold.createAttributes().build());
		event.put(GaiaRegistry.MANDRAGORA.getEntityType(), Mandragora.createAttributes().build());
		event.put(GaiaRegistry.MATANGO.getEntityType(), Matango.createAttributes().build());
		event.put(GaiaRegistry.MERMAID.getEntityType(), Mermaid.createAttributes().build());
		event.put(GaiaRegistry.MINOTAURUS.getEntityType(), Minotaurus.createAttributes().build());
		event.put(GaiaRegistry.MUMMY.getEntityType(), Mummy.createAttributes().build());
		event.put(GaiaRegistry.MINOTAUR.getEntityType(), Minotaur.createAttributes().build());
		event.put(GaiaRegistry.MIMIC.getEntityType(), Mimic.createAttributes().build());
		event.put(GaiaRegistry.NAGA.getEntityType(), Naga.createAttributes().build());
		event.put(GaiaRegistry.NINE_TAILS.getEntityType(), NineTails.createAttributes().build());
		event.put(GaiaRegistry.ONI.getEntityType(), Oni.createAttributes().build());
		event.put(GaiaRegistry.ORC.getEntityType(), Orc.createAttributes().build());
		event.put(GaiaRegistry.SATYRESS.getEntityType(), Satyress.createAttributes().build());
		event.put(GaiaRegistry.SHAMAN.getEntityType(), Shaman.createAttributes().build());
		event.put(GaiaRegistry.SHARKO.getEntityType(), Sharko.createAttributes().build());
		event.put(GaiaRegistry.SIREN.getEntityType(), Siren.createAttributes().build());
		event.put(GaiaRegistry.SLUDGE_GIRL.getEntityType(), SludgeGirl.createAttributes().build());
		event.put(GaiaRegistry.SPHINX.getEntityType(), Sphinx.createAttributes().build());
		event.put(GaiaRegistry.SPORELING.getEntityType(), Sporeling.createAttributes().build());
		event.put(GaiaRegistry.SPRIGGAN.getEntityType(), Spriggan.createAttributes().build());
		event.put(GaiaRegistry.SUCCUBUS.getEntityType(), Succubus.createAttributes().build());
		event.put(GaiaRegistry.TOAD.getEntityType(), Toad.createAttributes().build());
		event.put(GaiaRegistry.VALKYRIE.getEntityType(), Valkyrie.createAttributes().build());
		event.put(GaiaRegistry.WERECAT.getEntityType(), Werecat.createAttributes().build());
		event.put(GaiaRegistry.WITCH.getEntityType(), Witch.createAttributes().build());
		event.put(GaiaRegistry.WITHER_COW.getEntityType(), WitherCow.createAttributes().build());
		event.put(GaiaRegistry.WIZARD_HARPY.getEntityType(), WizardHarpy.createAttributes().build());
		event.put(GaiaRegistry.YUKI_ONNA.getEntityType(), YukiOnna.createAttributes().build());

		event.put(GaiaRegistry.HORSE.getEntityType(), GaiaHorse.createBaseHorseAttributes().build());

		event.put(GaiaRegistry.TRADER.getEntityType(), Trader.createAttributes().build());
		event.put(GaiaRegistry.CREEPER_GIRL.getEntityType(), CreeperGirl.createAttributes().build());
		event.put(GaiaRegistry.ENDER_GIRL.getEntityType(), EnderGirl.createAttributes().build());
//		event.put(GaiaRegistry.HOLSTAURUS.getEntityType(), Holstaurus.createAttributes().build());
		event.put(GaiaRegistry.SLIME_GIRL.getEntityType(), SlimeGirl.createAttributes().build());
//		event.put(GaiaRegistry.WERESHEEP.getEntityType(), Weresheep.createAttributes().build());
	}
}
